Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-12, with the labels that each got.

#493 added additional sys calls to whitelist req as part of node upgrade
  deployment_hooks/config/settings.yml
Labels: PipeLine:Green, unscheduled

#494 Feature/inter operator
  interoperator/config/crds/osb_v1alpha1_plan.yaml
  interoperator/config/samples/osb_v1alpha1_plan.yaml
  interoperator/config/samples/osb_v1alpha1_plan2.yaml
  interoperator/config/samples/osb_v1alpha1_plan3.yaml
  interoperator/config/samples/templates/blueprint/templates/configmap.yaml
  interoperator/config/samples/templates/blueprint/values.yaml
  interoperator/pkg/apis/osb/v1alpha1/plan_types.go
  interoperator/pkg/controller/serviceinstance/serviceinstance_controller.go
  interoperator/pkg/internal/renderer/factory/factory.go
Labels: unscheduled

#497 Change Teamplate path to url
  interoperator/config/crds/osb_v1alpha1_plan.yaml
  interoperator/config/default/manager_image_patch.yaml
  interoperator/config/samples/osb_v1alpha1_plan.yaml
  interoperator/config/samples/osb_v1alpha1_plan2.yaml
  interoperator/config/samples/osb_v1alpha1_plan3.yaml
  interoperator/pkg/apis/osb/v1alpha1/plan_types.go
  interoperator/pkg/internal/renderer/factory/factory.go
Labels: unscheduled

#496 Adding postgresql service and plan samples
  api-controllers/ServiceBrokerApiController.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  interoperator/config/samples/osb_v1alpha1_plan4.yaml
  interoperator/config/samples/osb_v1alpha1_service2.yaml
Labels: unscheduled

#498 Set ownerReference for Plans as service
  interoperator/Dockerfile
  interoperator/pkg/controller/plan/plan_controller.go
  interoperator/pkg/controller/serviceinstance/serviceinstance_controller.go
  interoperator/pkg/internal/services/services.go
Labels: unscheduled

#468 Modifying DbManager init flow to store/fetch credentials on ApiServer
  broker/lib/fabrik/DBManager.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/test_broker/fabrik.DBManager.spec.js
  test/test_broker/operators.DirectorService.spec.js
Labels: PipeLine:Green

#454 Initial changes for supporting k8s consumption of lifecycle operations and bind/unbind via SM
  api-controllers/ServiceFabrikApiController.js
  api-controllers/routes/api/v1.js
  operators/bosh-operator/DirectorService.js
  platform-managers/BasePlatformManager.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
Labels: PipeLine:Green, unscheduled

#499 Update Golang version for interoperator
  interoperator/Dockerfile
  interoperator/config/default/manager_image_patch.yaml
  interoperator/config/samples/templates/postgresqlProperties/templates/properties.yaml
Labels: unscheduled

#508 Fix test
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: DO NOT MERGE, DRAFT, not-ready-for-review, unscheduled

#511 Increase Coverage
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/acceptance/service-broker-api.catalog.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
Labels: unscheduled

#505 Including update params in manifest
  broker/config/templates/blueprint-manifest.yml.ejs
Labels: unscheduled

#515 Muliple cluster support except watch
  interoperator/config/crds/osb_v1alpha1_sfservicebinding.yaml
  interoperator/config/samples/osb_v1alpha1_sfplan5.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/apis/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/internal/cluster/cluster.go
  interoperator/pkg/internal/cluster/factory/factory.go
  interoperator/pkg/internal/properties/properties.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#518 Feature/inter operator
  api-controllers/ServiceBrokerApiController.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#519 Persist the created subresources in status
  interoperator/Gopkg.lock
  interoperator/Gopkg.toml
  interoperator/config/crds/osb_v1alpha1_sfplan.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfplan_types.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#520 Fix bind
  api-controllers/ServiceBrokerApiController.js
  data-access-layer/eventmesh/ApiServerClient.js
Labels: unscheduled

#522 Handling cases where the configmap/config doesnt exist
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
Labels: unscheduled

#523 Bug fix for selective update feature
  jobs/ServiceInstanceUpdateJob.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
Labels: unscheduled

#516 [Feature/Multi-tenancy] Adding multitenancy-operator
  broker/config/crds/bind.servicefabrik.io_v1alpha1_postgresqlmtbinds.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_postgresqlmts.yaml
  broker/config/settings.yml
  broker/config/templates/postgresql-manifest.yml.ejs
  common/constants.js
  operators/StartPostgresqlMTOperators.js
  operators/multitenancy-operator/MTServiceFabrik.js
  operators/multitenancy-operator/MultitenancyAgent.js
  operators/multitenancy-operator/MultitenancyBindOperator.js
  operators/multitenancy-operator/MultitenancyBindService.js
  operators/multitenancy-operator/MultitenancyOperator.js
  operators/multitenancy-operator/MultitenancyService.js
  test/test_broker/acceptance/service-broker-api.catalog.spec.js
  test/test_broker/acceptance/service-broker-api.instances.multitenancy.spec.js
  test/test_broker/mocks/index.js
  test/test_broker/mocks/multitenancyAgent.js
  test/test_broker/operators.MultitenancyOperator.spec.js
  test/test_broker/operators.MultitenancyService.spec.js
Labels: unscheduled

#527 [interoperator] Special handling for director delete
  interoperator/config/samples/osb_v1alpha1_sfplan.yaml
  interoperator/config/samples/osb_v1alpha1_sfplan2.yaml
  interoperator/config/samples/osb_v1alpha1_sfplan3.yaml
  interoperator/config/samples/osb_v1alpha1_sfplan4.yaml
  interoperator/config/samples/osb_v1alpha1_sfplan5.yaml
  interoperator/config/samples/osb_v1alpha1_sfservice.yaml
  interoperator/config/samples/osb_v1alpha1_sfservice2.yaml
  interoperator/config/samples/templates/gotemplates/director/properties.yaml
  interoperator/config/samples/templates/gotemplates/director/provision.yaml
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/internal/renderer/gotemplate/fuctions.go
  interoperator/pkg/internal/renderer/gotemplate/renderer.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#529 Add director bind template
  api-controllers/ServiceBrokerApiController.js
  interoperator/config/samples/templates/gotemplates/director/bind.yaml
  interoperator/config/samples/templates/gotemplates/director/properties.yaml
  interoperator/config/samples/templates/gotemplates/director/sources.yaml
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/internal/properties/properties.go
  interoperator/pkg/internal/resources/resources.go
  operators/bosh-operator/BoshBindOperator.js
Labels: unscheduled
