Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-07, with the labels that each got.

#310 Fix Controller Handler
  broker/lib/controllers/FabrikBaseController.js
Labels: unscheduled

#311 Fix/default bm
  broker/lib/controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/UnlockResourcePoller.js
  broker/lib/middleware.js
  eventmesh/LockManager.js
  managers/backup-manager/DefaultBackupManager.js
Labels: unscheduled

#312 Check backup support for last backup
  broker/lib/controllers/ServiceFabrikApiController.js
Labels: unscheduled

#313 Catch Unprocessable error in scheduleBackup job
  broker/lib/jobs/ScheduleBackupJob.js
  common/utils/HttpClient.js
Labels: unscheduled

#316 Decrease apiserver loadspec calls
  eventmesh/ApiServerClient.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/support/index.js
Labels: unscheduled

#317 Get logs from backupstore
  broker/lib/controllers/ServiceFabrikApiController.js
  managers/backup-manager/BackupService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/managers.BackupService.spec.js
Labels: unscheduled

#318 Fix misreporting of etcd lock failed error in logs
  broker/lib/fabrik/LockStatusPoller.js
  test/test_broker/fabrik.LockStatusPoller.spec.js
Labels: unscheduled

#320 Fix for the maintainance mode state
  common/constants.js
Labels: unscheduled

#309 Feature/fine grained sec groups
  broker/lib/fabrik/CfPlatformManager.js
  broker/lib/fabrik/DirectorInstance.js
  broker/lib/models/Service.js
  test/test_broker/fabrik.CfPlatformManager.spec.js
  test/test_broker/models.Service.spec.js
Labels: DO NOT MERGE, unscheduled

#322 Allow not staggering scheduled updates through CF parameter
  broker/lib/controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/DBManager.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/ServiceFabrikOperation.js
  broker/lib/jobs/ServiceInstanceUpdateJob.js
  test/test_broker/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/fabrik.DirectorInstance.spec.js
  test/test_broker/fabrik.DirectorManager.spec.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
Labels: unscheduled

#323 Allow not staggering scheduled updates through CF parameter
  broker/lib/controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/DBManager.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/ServiceFabrikOperation.js
  broker/lib/jobs/ServiceInstanceUpdateJob.js
  test/test_broker/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/fabrik.DirectorInstance.spec.js
  test/test_broker/fabrik.DirectorManager.spec.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
Labels: unscheduled

#321 Fix/refactor
  broker/lib/jobs/BnRStatusPollerJob.js
  eventmesh/ApiServerClient.js
  managers/BaseDirectorService.js
  managers/backup-manager/BackupService.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/managers.BaseDirectorService.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
Labels: SF2.0

#315 Refactoring the middleware and LockManager
  broker/lib/middleware.js
  broker/lib/routes/broker/v2.js
  eventmesh/LockManager.js
  test/test_broker/eventmesh.LockManager.spec.js
Labels: SF2.0, unscheduled

#324 Add Base Manager
  eventmesh/ApiServerClient.js
  managers/BaseManager.js
  managers/StartBackupRestoreManagers.js
  managers/backup-manager/DefaultBackupManager.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/managers.DefaultBackupManager.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
Labels: PipeLine:Green, SF2.0, unscheduled

#328 Enhance the broker agent bind response to include network details
  broker/config/route-registrar.json
  broker/lib/docker/DockerCredentials.js
  common/constants.js
  test/test_broker/docker.DockerCredentials.spec.js
Labels: PipeLine:Green

#332 Forward the prebind action to the agent
  broker/lib/fabrik/Agent.js
  broker/lib/fabrik/DirectorManager.js
  test/test_broker/fabrik.Agent.spec.js
Labels: unscheduled

#327 Forward prebind action to the agent
  broker/lib/fabrik/DirectorManager.js
  data-access-layer/service-agent/Agent.js
  test/test_broker/fabrik.Agent.spec.js
Labels: unscheduled

#333 Add documentation for the prebind and preunbind actions
  src/content/api/agent/v1.0/requests/credentials_create.apib
  src/content/api/agent/v1.0/requests/credentials_delete.apib
Labels: unscheduled

#331 Transition sfv2
  api-controllers/ServiceFabrikApiController.js
  common/constants.js
  data-access-layer/cf/CloudControllerClient.js
  data-access-layer/eventmesh/ApiServerClient.js
  managers/backup-manager/BackupService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/mocks/cloudController.js
Labels: PipeLine:Green, unscheduled

#337 Add error field
  broker/lib/fabrik/UnlockResourcePoller.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  managers/backup-manager/BackupService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/managers.BackupService.spec.js
Labels: unscheduled

#342 Fix ongoing backup
  data-access-layer/eventmesh/ApiServerClient.js
  jobs/BnRStatusPollerJob.js
  managers/backup-manager/BackupService.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/managers.BackupService.spec.js
Labels: unscheduled

#340 Fix ongoing backup
  data-access-layer/eventmesh/ApiServerClient.js
  jobs/BnRStatusPollerJob.js
  managers/backup-manager/BackupService.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/managers.BackupService.spec.js
Labels: PipeLine:Green, SF2.0, unscheduled

#338 Fix kubernetes-client version
  package.json
Labels: SF2.0, unscheduled

#339 Allow updates via Admin API to run immediately
  api-controllers/ServiceFabrikAdminController.js
Labels: unscheduled

#334 Add apiserver ip property
  broker/config/settings.yml
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
Labels: PipeLine:Green, SF2.0, unscheduled

#344 Change setTimeout to use Promise.Delay
  broker/lib/fabrik/UnlockResourcePoller.js
  common/constants.js
  managers/BaseManager.js
Labels: PipeLine:Green, SF2.0, unscheduled
