Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-05, with the labels that each got.

#266 Feature/iptables manager
  config/settings.yml
  config/templates/blueprint-manifest.yml.ejs
  lib/bosh/index.js
  lib/bosh/manifest/Addons.js
  lib/bosh/manifest/Header.js
  lib/constants.js
  lib/fabrik/DBManager.js
  lib/fabrik/DirectorManager.js
  test/bosh.manifest.AddOns.spec.js
  test/bosh.manifest.Header.spec.js
  test/fabrik.DBManager.spec.js
  test/fabrik.DirectorManager.spec.js
Labels: DO NOT MERGE, unscheduled

#274 Feature/etcd-lock-manager
  broker/config/certs/etcd-ca.crt
  broker/config/certs/etcd.crt
  broker/config/certs/etcd.key
  broker/config/settings.yml
  common/errors.js
  eventmesh/Etcd3EventMeshServer.js
  eventmesh/LockManager.js
  eventmesh/config.js
  eventmesh/constants.js
  eventmesh/index.js
  eventmesh/settings.yml
  test/eventmesh.LockManager.spec.js
Labels: unscheduled

#279 Fixing null pointer exception
  broker/lib/fabrik/DirectorManager.js
Labels: unscheduled

#275 Feature/bnr status poller
  broker/lib/cf/ServiceFabrikClient.js
  broker/lib/controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/Agent.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/FabrikStatusPoller.js
  broker/lib/fabrik/OobBackupManager.js
  broker/lib/jobs/BnRStatusPollerJob.js
  broker/lib/jobs/JobFabrik.js
  broker/lib/routes/api/v1.js
  common/constants.js
  test/acceptance/service-fabrik-api.instances.director.spec.js
  test/fabrik.Agent.spec.js
  test/fabrik.FabrikStatusPoller.spec.js
  test/fabrik.OOBBackupManager.spec.js
  test/jobs.BnRStatusPollerJob.spec.js
  test/jobs.JobFabrik.spec.js
  test/mocks/agent.js
  test/mocks/serviceFabrikClient.js
Labels: DO NOT MERGE, High Availability, unscheduled

#288 Fix parsing of space_guid from context during security group creation of Update Service flow
  broker/lib/fabrik/CfPlatformManager.js
Labels: unscheduled

#277 Bug/dashboard
  broker/lib/bosh/BoshDirectorClient.js
  broker/lib/fabrik/DirectorInstance.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/DockerInstance.js
  test/test_broker/acceptance/dashboard.docker.spec.js
  test/test_broker/acceptance/service-broker-api.instances.director.spec.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/mocks/cloudController.js
Labels: unscheduled

#284 Changed logic of BnR status poller
  broker/lib/cf/ServiceFabrikClient.js
  broker/lib/controllers/ServiceFabrikApiController.js
  broker/lib/jobs/BnRStatusPollerJob.js
  broker/lib/routes/api/v1.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/cf.ServiceFabrikClient.spec.js
  test/test_broker/jobs.BnRStatusPollerJob.spec.js
Labels: DO NOT MERGE, High Availability, SF2.0, enhancement, unscheduled
