Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-11, with the labels that each got.

#459 Keep creating binding property for sf-mongodb bind
  operators/bosh-operator/DirectorService.js
  test/test_broker/mocks/director.js
  test/test_broker/operators.DirectorService.spec.js
Labels: unscheduled

#461 [rel-10b]Keep creating binding property for sf-mongodb bind (#459)
  operators/bosh-operator/DirectorService.js
  test/test_broker/mocks/director.js
  test/test_broker/operators.DirectorService.spec.js
Labels: unscheduled

#463 Fixing the query criteria for purging jobdetails collection
  jobs/ScheduleManager.js
Labels: unscheduled

#441 Dashboard url would be updated with new plan in patch api response and format changed
  api-controllers/DashboardController.js
  api-controllers/ServiceBrokerApiController.js
  api-controllers/routes/manage.js
  broker/lib/fabrik/BaseManager.js
  broker/lib/fabrik/DirectorInstance.js
  broker/lib/fabrik/DockerInstance.js
  broker/lib/fabrik/VirtualHostInstance.js
  common/views/mixins/sections.pug
  test/test_broker/acceptance/dashboard.director.spec.js
  test/test_broker/acceptance/dashboard.docker.spec.js
  test/test_broker/acceptance/dashboard.virtualHost.spec.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  test/test_broker/acceptance/service-broker-api.instances.virtualHost.spec.js
  test/test_broker/mocks/uaa.js
Labels: DO NOT MERGE, unscheduled

#465 fixing the invocation of makeRequest by passing deploymentName
  data-access-layer/bosh/BoshDirectorClient.js
Labels: unscheduled

#462 implemented logic to enable multi-az only for internal users
  api-controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/DBManager.js
  common/constants.js
  operators/bosh-operator/DirectorService.js
  platform-managers/BasePlatformManager.js
  platform-managers/CfPlatformManager.js
  test/test_broker/fabrik.CfPlatformManager.spec.js
  test/test_broker/operators.DirectorService.ratelimits.spec.js
Labels: unscheduled

#466 Fix the missing import
  platform-managers/BasePlatformManager.js
Labels: unscheduled

#458 Feature/multi az migration
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceBrokerApiController.js
  broker/config/crds/serviceflow.servicefabrik.io_v1alpha1_serialserviceflows.yaml
  broker/config/crds/serviceflow.servicefabrik.io_v1alpha1_tasks.yaml
  broker/config/settings.yml
  broker/config/templates/blueprint-manifest.yml.ejs
  common/constants.js
  common/utils/ServiceFlowMapper.js
  data-access-layer/eventmesh/ApiServerClient.js
  operators/BaseOperator.js
  operators/serviceflow-operator/SerialServiceFlowOperator.js
  operators/serviceflow-operator/StartSerialServiceFlow.js
  operators/serviceflow-operator/serial-serviceflow-definition.yml
  operators/serviceflow-operator/task/BlueprintTask.js
  operators/serviceflow-operator/task/ServiceInstanceBackupTask.js
  operators/serviceflow-operator/task/ServiceInstanceUpdateTask.js
  operators/serviceflow-operator/task/Task.js
  operators/serviceflow-operator/task/TaskFabrik.js
  operators/serviceflow-operator/task/TaskOperator.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/operators.BOSHManager.spec.js
  test/test_broker/operators.DefaultBackupManager.spec.js
  test/test_broker/operators.DockerManager.spec.js
  test/test_broker/operators.VirtualHostManager.spec.js
  test/test_broker/operators.serviceflow.SerialWorkFlow.spec.js
  test/test_broker/operators.serviceflow.tasks.BlueprintTask.spec.js
  test/test_broker/operators.serviceflow.tasks.ServiceInstanceBackupTask.spec.js
  test/test_broker/operators.serviceflow.tasks.ServiceInstanceUpdateTask.spec.js
  test/test_broker/operators.serviceflow.tasks.Task.spec.js
  test/test_broker/operators.serviceflow.tasks.TaskFabrik.spec.js
  test/test_broker/operators.serviceflow.tasks.TaskOperator.spec.js
  test/test_broker/utils.ServiceflowMapper.js
Labels: PipeLine:Green, unscheduled

#469 Throw exception when deployment name is not present in task id
  data-access-layer/bosh/BoshDirectorClient.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
Labels: PipeLine:Green, unscheduled

#470 Adding indexes for nested objects in mongodb collections
  data-access-layer/db/EventDetailSchema.js
  data-access-layer/db/JobDetailSchema.js
  data-access-layer/db/JobRunDetailSchema.js
Labels: unscheduled

#475 fix: context object sent during schedule update required check
  api-controllers/ServiceFabrikApiController.js
  broker/config/templates/blueprint-manifest.yml.ejs
  operators/bosh-operator/BoshStaggeredDeploymentPoller.js
  platform-managers/CfPlatformManager.js
Labels: unscheduled

#476 fix: isMultiAzDeploymentEnabled caller to evaluate promise response
  operators/bosh-operator/DirectorService.js
  test/test_broker/fabrik.DBManager.spec.js
  test/test_broker/operators.DirectorService.ratelimits.spec.js
Labels: unscheduled

#473 Remove dependency on director
  common/utils/HttpClient.js
  data-access-layer/bosh/BoshDirectorClient.js
  data-access-layer/eventmesh/ApiServerClient.js
  operators/BaseOperator.js
Labels: unscheduled

#481 Clean up ServiceFabrikOperation and FabrikStatusPoller
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/routes/admin.js
  broker/lib/fabrik/Fabrik.js
  broker/lib/fabrik/FabrikStatusPoller.js
  broker/lib/fabrik/ServiceFabrikOperation.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
Labels: PipeLine:Green, unscheduled

#482 renaming the crds
  broker/config/crds/osb.servicefabrik.io_v1alpha1_plans.yaml
  broker/config/crds/osb.servicefabrik.io_v1alpha1_serviceinstances.yaml
  broker/config/crds/osb.servicefabrik.io_v1alpha1_services.yaml
Labels: unscheduled

#483 Remove status subreource
  interoperator/config/crds/osb_v1alpha1_plan.yaml
  interoperator/config/crds/osb_v1alpha1_service.yaml
  interoperator/config/crds/osb_v1alpha1_serviceinstance.yaml
  interoperator/config/samples/osb_v1alpha1_plan.yaml
  interoperator/pkg/apis/osb/v1alpha1/plan_types.go
  interoperator/pkg/apis/osb/v1alpha1/service_types.go
  interoperator/pkg/apis/osb/v1alpha1/serviceinstance_types.go
  interoperator/pkg/apis/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/pkg/controller/serviceinstance/serviceinstance_controller.go
Labels: unscheduled

#480 Fix: Upgrade workflow is running with READ Lock type
  api-controllers/FabrikBaseController.js
  common/constants.js
  operators/BaseOperator.js
  operators/serviceflow-operator/SerialServiceFlowOperator.js
  test/test_broker/operators.serviceflow.SerialServiceFlow.spec.js
  test/test_broker/operators.serviceflow.tasks.TaskOperator.spec.js
Labels: PipeLine:Green, unscheduled

#471 Using crd to store vhost relationship with deployment
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
  broker/config/settings.yml
  broker/lib/fabrik/VirtualHostRelationMapper.js
  data-access-layer/eventmesh/ApiServerClient.js
  data-access-layer/iaas/VirtualHostStore.js
  data-access-layer/iaas/index.js
  operators/virtualhost-operator/VirtualHostOperator.js
  operators/virtualhost-operator/VirtualHostRelationMapper.js
  test/test_broker/acceptance/dashboard.virtualHost.spec.js
  test/test_broker/operators.VirtualHostManager.spec.js
  test/test_broker/operators.VirtualHostService.spec.js
Labels: unscheduled

#487 Added login_hint parameter in authorizationUrl
  data-access-layer/cf/UaaClient.js
  test/test_broker/cf.UaaClient.spec.js
  test/test_broker/mocks/uaa.js
Labels: unscheduled

#485 Adding login_hint parameter in authorizationUrl
  data-access-layer/cf/UaaClient.js
  test/test_broker/cf.UaaClient.spec.js
  test/test_broker/mocks/uaa.js
Labels: unscheduled

#490 Adding support for query parameter specifying login_hint in dashboard URL
  api-controllers/DashboardController.js
  data-access-layer/cf/UaaClient.js
  test/test_broker/cf.UaaClient.spec.js
  test/test_broker/mocks/uaa.js
Labels: unscheduled

#489 Adding support for query parameter specifying login_hint in dashboard URL
  api-controllers/DashboardController.js
  data-access-layer/cf/UaaClient.js
  test/test_broker/cf.UaaClient.spec.js
  test/test_broker/mocks/uaa.js
Labels: unscheduled

#479 Fix backup deletion bug
  api-controllers/ServiceFabrikApiController.js
  data-access-layer/cf/ServiceFabrikClient.js
  data-access-layer/iaas/BackupStore.js
  jobs/ScheduleBackupJob.js
  test/test_broker/jobs.ScheduleBackupJob.spec.js
  test/test_broker/mocks/serviceFabrikClient.js
Labels: PipeLine:Green, unscheduled
