Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-03, with the labels that each got.

#207 Catalog handling to filter plans/services in case of cross consumption
  config/settings.yml
  lib/constants.js
  lib/controllers/ServiceBrokerApiController.js
  lib/fabrik/BasePlatformManager.js
  lib/fabrik/CfPlatformManager.js
  lib/fabrik/DirectorInstance.js
  lib/fabrik/DockerInstance.js
  lib/fabrik/Fabrik.js
  lib/fabrik/K8sPlatformManager.js
  lib/fabrik/VirtualHostInstance.js
  lib/routes/broker/index.js
  lib/routes/broker/v2.js
  lib/routes/index.js
  server.js
  test/acceptance/service-broker-api.catalog.spec.js
  test/fabrik.ServiceBrokerApi.spec.js
  test/quota.QuotaManager.spec.js
  test/support/apps.js
Labels: DO NOT MERGE, unscheduled

#215 Feature/deployment hooks
  config/settings.yml
  config/templates/actions/Blueprint_PreCreate
  config/templates/actions/ReserveIps.js
  config/templates/blueprint-manifest.yml.ejs
  lib/LoadDeploymentActions.js
  lib/config.js
  lib/constants.js
  lib/controllers/BaseController.js
  lib/controllers/DashboardController.js
  lib/controllers/ServiceBrokerApiController.js
  lib/fabrik/DBManager.js
  lib/fabrik/DirectorManager.js
  lib/fabrik/actions/ActionManager.js
  lib/fabrik/actions/js/BaseAction.js
  lib/utils/ScriptExecutor.js
  lib/utils/index.js
  package.json
  test/fabrik.DirectorManager.spec.js
  test/support/index.js
  test/utils.ScriptExecutor.spec.js
Labels: DO NOT MERGE, unscheduled

#222 Fix for the blank security group creation problem
  config/eventlog-config-internal.yml
  lib/fabrik/CfPlatformManager.js
  lib/fabrik/DirectorInstance.js
  lib/fabrik/DockerInstance.js
  test/EventLogInterceptor.spec.js
  test/acceptance/service-broker-api.catalog.spec.js
Labels: unscheduled

#223 Update version for moment library
  .gitignore
  package.json
Labels: unscheduled

#224 Fixes following scheduler issues:
  JobScheduler.js
  config/settings.yml
  lib/constants.js
  lib/db/Repository.js
  lib/jobs/BaseJob.js
  lib/jobs/ScheduledOobDeploymentBackupJob.js
  lib/maintenance/MaintenanceManager.js
  lib/routes/broker/v2.js
  test/jobs.ScheduledOobDeploymentBackupJob.spec.js
Labels: unscheduled

#220 Fix/issue deployment ip cache 200
  lib/bosh/BoshDirectorClient.js
  lib/fabrik/DirectorManager.js
  lib/utils/HttpClient.js
  test/acceptance/service-broker-api.instances.director.spec.js
  test/acceptance/service-broker-api.instances.virtualHost.spec.js
  test/acceptance/service-fabrik-admin.deployments.backups.director.spec.js
  test/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/acceptance/service-fabrik-api.instances.director.spec.js
  test/bosh.BoshDirectorClient.spec.js
  test/fabrik.OOBBackupManager.spec.js
  test/mocks/director.js
Labels: unscheduled

#225 Fix for the issue 212
  lib/constants.js
  lib/controllers/ServiceBrokerApiController.js
  lib/errors.js
  lib/middleware.js
  test/acceptance/service-broker-api.instances.director.spec.js
  test/acceptance/service-fabrik-api.instances.director.spec.js
  test/middleware.spec.js
Labels: unscheduled

#227 Fix for #185 - Deleting 14 days older backup forcefully
  lib/jobs/ScheduledOobDeploymentBackupJob.js
Labels: unscheduled

#230 Improve scheduler maintenance mode
  JobScheduler.js
  lib/cf/ServiceFabrikClient.js
  lib/constants.js
  lib/controllers/ServiceFabrikApiController.js
  lib/fabrik/DBManager.js
  test/JobScheduler.spec.js
  test/acceptance/service-fabrik-api.info.spec.js
  test/cf.ServiceFabrikClient.spec.js
  test/fabrik.DBManager.spec.js
Labels: unscheduled

#229 Bubble up iaas error
  lib/iaas/AzureClient.js
  lib/iaas/CloudProviderClient.js
  test/iaas.AzureClient.spec.js
  test/iaas.CloudProviderClient.js
  test/mocks/azureClient.js
Labels: unscheduled

#232 Randomising schedule interval when input with hours
  JobScheduler.js
  lib/jobs/ScheduleManager.js
  lib/utils/ScriptExecutor.js
  lib/utils/index.js
  package.json
  test/jobs.ScheduleManager.spec.js
  test/support/index.js
  test/utils.spec.js
Labels: DO NOT MERGE, sprint-3a, unscheduled

#233 Introduced new changes for Code Coverage using Coveralls.io
  .travis.yml
  package.json
  test/global.setup.js
Labels: unscheduled

#235 Changing the settings.yml and adding a cloud-config for boshlite
  README.md
  config/cloud-config.yml
  config/settings.yml
Labels: unscheduled

#239 Fixes issue 237 and 238
  config/eventlog-config-internal.yml
  lib/fabrik/DirectorInstance.js
  test/acceptance/service-broker-api.instances.director.spec.js
Labels: unscheduled

#236 Fix scheduler poll issue during maintenance
  JobScheduler.js
Labels: unscheduled

#241 Bluebird Promise referred instead of default promise
  lib/jobs/ScheduledOobDeploymentBackupJob.js
Labels: bug, unscheduled

#242 Bluebird Promise referred instead of default promise
  lib/jobs/ScheduledOobDeploymentBackupJob.js
Labels: bug, unscheduled
