Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-10, with the labels that each got.

#425 Remove unnecessary error logs from codebase
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/CfPlatformManager.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/DirectorTaskPoller.js
  broker/lib/fabrik/DockerInstance.js
  data-access-layer/eventmesh/LockManager.js
  managers/backup-manager/BackupStatusPoller.js
  managers/bosh-manager/BoshManager.js
  managers/restore-manager/RestoreTaskPoller.js
Labels: unscheduled

#423 Add response in case of error in backup trigger
  managers/backup-manager/BackupService.js
Labels: unscheduled

#421 Changes for start restore api: support for PITR
  api/broker_v1.0.html
  src/content/api/broker/v1.0/index.apib
  src/content/api/broker/v1.0/requests/POST_service_instances_instanceGuid_restore.apib
  src/content/api/broker/v1.0/responses/400.apib
Labels: unscheduled

#427 Event logging for sf internal update operations
  common/constants.js
  managers/bosh-manager/BoshManager.js
  managers/bosh-manager/BoshTaskPoller.js
Labels: unscheduled

#430 Modifying unbind flow to fetch the credentials from ApiServer first
  managers/bosh-manager/DirectorService.js
  test/test_broker/managers.DirectorService.spec.js
Labels: unscheduled

#431 Enable schemas in the service plan
  common/models/Plan.js
Labels: unscheduled

#426 Add Base Poller
  common/constants.js
  managers/BaseStatusPoller.js
  managers/StartBackupRestoreManagers.js
  managers/StartBoshManagers.js
  managers/backup-manager/BackupStatusPoller.js
  managers/bosh-manager/BoshTaskStatusPoller.js
  managers/restore-manager/RestoreStatusPoller.js
  managers/restore-manager/RestoreTaskPoller.js
  test/test_broker/managers.BackupStatusPoller.js
  test/test_broker/managers.BaseStatusPoller.spec.js
Labels: PipeLine:Green, SF2.0

#433 Make restore poller frequency equal to backup frequency
  common/constants.js
  managers/bosh-manager/BoshTaskPoller.js
  managers/restore-manager/RestoreStatusPoller.js
Labels: unscheduled

#429 Use weekly cron for scheduled update
  common/utils/index.js
  jobs/ServiceInstanceUpdateJob.js
  test/test_broker/jobs.ScheduleManager.spec.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
  test/test_broker/utils.spec.js
Labels: PipeLine:Green, unscheduled

#432 Adding Indexes to JobDetails/JobRunDetails schema MongoDB
  data-access-layer/db/JobDetailSchema.js
  data-access-layer/db/JobRunDetailSchema.js
Labels: unscheduled

#434 Modifying BoshTaskStatusPoller to update deployment IPs in deployment resources
  managers/bosh-manager/BoshTaskStatusPoller.js
Labels: unscheduled

#428 Modifying flow of getDeploymentIps to fetch IPs from ApiServer
  api-controllers/ServiceFabrikAdminController.js
  common/utils/index.js
  data-access-layer/bosh/BoshDirectorClient.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/managers.DirectorService.spec.js
  test/test_broker/managers.RestoreService.spec.js
  test/test_broker/managers.VirtualHostService.spec.js
Labels: unscheduled

#437 Removing createBindingProperty on Bosh from bind flow and deleteBindingProperty from unbind flow
  operators/bosh-operator/DirectorService.js
  test/test_broker/operators.DirectorService.spec.js
Labels: unscheduled

#443 fixed js format issues
  common/constants.js
  operators/docker-operator/DockerService.js
Labels: unscheduled

#446 Checkmarx Fix : Missing HSTS Header for dashboard controller
  common/ExpressApp.js
  package.json
Labels: unscheduled

#438 Supporting service manager with CF platform
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceBrokerApiController.js
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/ServiceFabrikApiController.js
  api-controllers/routes/broker/v2.js
  broker/config/settings.yml
  broker/lib/fabrik/BasePlatformManager.js
  broker/lib/fabrik/Fabrik.js
  broker/lib/fabrik/K8sPlatformManager.js
  broker/lib/middleware.js
  broker/server.js
  common/config/eventlog-config-internal.yml
  common/constants.js
  common/models/Plan.js
  data-access-layer/eventmesh/ApiServerClient.js
  operators/BaseService.js
  operators/backup-operator/BackupService.js
  operators/bosh-operator/DirectorService.js
  operators/docker-operator/DockerService.js
  test/test_broker/EventLogInterceptor.spec.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  test/test_broker/acceptance/service-broker-api.instances.virtualHost.spec.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/support/apps.js
Labels: service-manager

#449 Move platform managers from broker/lib/fabrik to platform-managers
  broker/lib/fabrik/Fabrik.js
  operators/bosh-operator/DirectorService.js
  operators/docker-operator/DockerService.js
  platform-managers/BasePlatformManager.js
  platform-managers/CfPlatformManager.js
  platform-managers/K8sPlatformManager.js
  test/test_broker/fabrik.CfPlatformManager.spec.js
Labels: unscheduled

#439 Try to get platform context from etcd in DirectorService before getting it from bosh
  broker/lib/fabrik/DirectorInstance.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/operators.DirectorService.spec.js
Labels: unscheduled

#424 Remove assignManager
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceFabrikApiController.js
  api-controllers/routes/api/v1.js
  broker/lib/fabrik/BaseManager.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/DockerManager.js
  common/utils/index.js
  operators/BaseService.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/broker.middleware.spec.js
  test/test_broker/fabrik.DirectorManager.spec.js
Labels: PipeLine:Green, unscheduled

#450 Added code for bosh resilience in create, update and delete flow.
  common/constants.js
  data-access-layer/bosh/BoshDirectorClient.js
  operators/bosh-operator/BoshOperator.js
  operators/bosh-operator/BoshStaggeredDeploymentPoller.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/operators.BoshstaggeredDeploymentPoller.spec.js
  test/test_broker/operators.DirectorService.ratelimits.spec.js
Labels: enhancement, unscheduled

#457 Remove sf2.0 migration from SBAC
  api-controllers/ServiceBrokerApiController.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#455 Add a new admin endpoint to return all instances with updates scheduled.
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/routes/admin.js
  test/test_broker/acceptance/service-fabrik-admin.updates.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/operators.DirectorService.ratelimits.spec.js
Labels: PipeLine:Green, unscheduled

#456 Update Lodhash version
  package.json
Labels: PipeLine:Green, unscheduled
