Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-09, with the labels that each got.

#387 Don't schedule backup if not PITR
  managers/restore-manager/RestoreService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/managers.RestoreService.spec.js
Labels: unscheduled

#388 Don't schedule backup if not PITR
  managers/restore-manager/RestoreService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/managers.RestoreService.spec.js
Labels: unscheduled

#391 Lowered log level of all requests to Debug to avoid clutter in log
  common/utils/HttpClient.js
Labels: unscheduled

#390 Removing assignInstance from V2 route
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceBrokerApiController.js
  api-controllers/routes/broker/v2.js
  broker/lib/fabrik/DirectorInstance.js
  broker/lib/fabrik/DirectorManager.js
  broker/lib/middleware.js
  common/EventLogInterceptor.js
  test/test_broker/EventLogInterceptor.spec.js
  test/test_broker/acceptance/dashboard.director.spec.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  test/test_broker/fabrik.DirectorInstance.spec.js
  test/test_broker/fabrik.DirectorManager.spec.js
  test/test_broker/mocks/director.js
Labels: PipeLine:Green, SF2.0, unscheduled

#394 Fixing the AssertionError import
  managers/bosh-manager/BoshTaskPoller.js
Labels: unscheduled

#348 Lock TTL Implementation for ApiServer locks
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceBrokerApiController.js
  api-controllers/ServiceFabrikApiController.js
  broker/config/settings.yml
  broker/lib/fabrik/UnlockResourcePoller.js
  broker/lib/middleware.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  data-access-layer/eventmesh/LockManager.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  test/test_broker/acceptance/service-broker-api.instances.virtualHost.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/cf.TokenIssuer.spec.js
  test/test_broker/eventmesh.LockManager.spec.js
  test/test_broker/fabrik.UnlockResourcePoller.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/managers.BOSHManager.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/managers.DefaultBackupManager.spec.js
  test/test_broker/managers.DockerManager.spec.js
  test/test_broker/managers.RestoreService.spec.js
  test/test_broker/managers.VirtualHostManager.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
Labels: PipeLine:Green, SF2.0

#397 Fix schedule autoupdate
  broker/lib/fabrik/ServiceFabrikOperation.js
  jobs/ServiceInstanceUpdateJob.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
Labels: unscheduled

#384 Fix unbounded runs of update jobs even into next cycle
  jobs/ScheduleManager.js
  jobs/Scheduler.js
  jobs/ServiceInstanceUpdateJob.js
  test/test_broker/jobs.Scheduler.spec.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
Labels: unscheduled

#398 Fixing delete event logging for 410 Gone response
  api-controllers/ServiceBrokerApiController.js
  common/EventLogInterceptor.js
  test/test_broker/EventLogInterceptor.spec.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#400 Reverse cred hub
  broker/config/settings.yml
  common/models/Service.js
  test/test_broker/models.Service.spec.js
Labels: unscheduled

#403 De-duplicate bosh link consumes from forbidden diff sections
  common/utils/index.js
Labels: unscheduled

#407 Do not create resource if not found in startBackuo
  api-controllers/ServiceFabrikApiController.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
Labels: unscheduled

#406 Do not create resource if not found in startBackup
  api-controllers/ServiceFabrikApiController.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
Labels: unscheduled

#408 Dashboard rendering: Fetching current plan of service instance while validation
  api-controllers/DashboardController.js
  broker/lib/fabrik/DirectorInstance.js
  broker/lib/fabrik/DockerInstance.js
  test/test_broker/acceptance/dashboard.director.spec.js
  test/test_broker/acceptance/dashboard.docker.spec.js
  test/test_broker/acceptance/dashboard.virtualHost.spec.js
  test/test_broker/mocks/cloudController.js
Labels: unscheduled

#409 prefix exe name to log file for better seggregation of logs in dev setup
  broker/config/settings.yml
Labels: unscheduled

#410 Fixing typo which was introduced during testing
  broker/config/settings.yml
Labels: unscheduled

#413 Improvement of test timings
  managers/docker-manager/DockerService.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  test/test_broker/acceptance/service-broker-api.instances.virtualHost.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.LockManager.spec.js
  test/test_broker/managers.BOSHManager.spec.js
  test/test_broker/managers.DefaultBackupManager.spec.js
  test/test_broker/managers.DockerManager.spec.js
  test/test_broker/managers.VirtualHostManager.spec.js
Labels: unscheduled

#411 Change BnRStatusPoller to ApiServer Based Poller from Scheduler Based
  common/constants.js
  jobs/BnRStatusPollerJob.js
  jobs/JobFabrik.js
  managers/StartBackupRestoreManagers.js
  managers/backup-manager/BackupService.js
  managers/backup-manager/BackupStatusPoller.js
  managers/backup-manager/DefaultBackupManager.js
  managers/bosh-manager/BoshTaskPoller.js
  managers/restore-manager/RestoreTaskPoller.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/jobs.BnRStatusPollerJob.spec.js
  test/test_broker/jobs.JobFabrik.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/managers.BackupStatusPoller.js
Labels: PipeLine:Green, SF2.0, unscheduled

#416 Remove error event on stream
  data-access-layer/eventmesh/ApiServerClient.js
Labels: unscheduled

#417 Clear poller when state is not in_progress
  managers/bosh-manager/BoshTaskPoller.js
Labels: unscheduled

#415 Added support to decouple cf update in admin update api
  api-controllers/ServiceFabrikAdminController.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
Labels: unscheduled

#419 Add annotation expiry logic
  common/constants.js
  managers/BaseManager.js
  test/test_broker/managers.BOSHManager.spec.js
Labels: unscheduled
