Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-08, with the labels that each got.

#346 Refactor APIServerClient Class
  api-controllers/ServiceFabrikApiController.js
  broker/lib/fabrik/UnlockResourcePoller.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  data-access-layer/eventmesh/LockManager.js
  jobs/BnRStatusPollerJob.js
  managers/BaseManager.js
  managers/backup-manager/BackupService.js
  managers/backup-manager/DefaultBackupManager.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/eventmesh.LockManager.spec.js
  test/test_broker/managers.DefaultBackupManager.spec.js
  test/test_broker/reports.BackupReportManager.spec.js
  test/test_deployment_hooks/mocks/index.js
Labels: PipeLine:Green, SF2.0, unscheduled

#335 Support for PITR
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/ServiceFabrikApiController.js
  broker/config/settings.yml
  broker/lib/fabrik/DirectorManager.js
  broker/lib/fabrik/OobBackupManager.js
  common/constants.js
  common/utils/index.js
  data-access-layer/iaas/BackupStore.js
  data-access-layer/iaas/BackupStoreForOob.js
  data-access-layer/iaas/BackupStoreForServiceInstance.js
  data-access-layer/iaas/GcpClient.js
  jobs/BackupReaperJob.js
  jobs/BnRStatusPollerJob.js
  jobs/ScheduleBackupJob.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-admin.deployments.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/iaas.GcpClient.spec.js
  test/test_broker/jobs.BackupReaperJobs.spec.js
  test/test_broker/jobs.ScheduleBackupJob.spec.js
  test/test_broker/mocks/serviceFabrikClient.js
  test/test_broker/utils.spec.js
Labels: DRAFT, Point In Time Recovery, unscheduled

#356 Clear Unlock intervals on watch refresh
  broker/lib/fabrik/UnlockResourcePoller.js
  data-access-layer/eventmesh/LockManager.js
  test/test_broker/eventmesh.LockManager.spec.js
  test/test_broker/fabrik.UnlockResourcePoller.js
Labels: PipeLine:Green, SF2.0, unscheduled

#351 Clear Unlock intervals on watch refresh
  broker/lib/fabrik/UnlockResourcePoller.js
  data-access-layer/eventmesh/LockManager.js
  test/test_broker/eventmesh.LockManager.spec.js
  test/test_broker/fabrik.UnlockResourcePoller.js
Labels: PipeLine:Green, SF2.0, unscheduled

#352 Remove service-fabrik backup v1 tests
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.backups.director.spec.js
Labels: unscheduled

#349 Support fabrik-internal services
  common/models/catalog.js
Labels: unscheduled

#361 Use more appropriate names
  managers/backup-manager/DefaultBackupManager.js
Labels: unscheduled

#341 Suffix service name to Riemann metric event
  common/models/catalog.js
  common/utils/EventLogRiemannClient.js
  test/test_broker/models.catalog.spec.js
  test/test_broker/utils.EventLogRiemannClient.spec.js
Labels: unscheduled

#359 Changes needed for the new apiserver
  api-controllers/ServiceFabrikApiController.js
  broker/config/crds/backup.servicefabrik.io_v1alpha1_defaultbackups.yaml
  broker/config/crds/backup.servicefabrik.io_v1alpha1_defaultrestores.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_directorbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_dockerbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_virtualhostbinds.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_directors.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_dockers.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
  broker/config/crds/lock.servicefabrik.io_v1alpha1_deploymentlocks.yaml
  broker/config/settings.yml
  broker/lib/fabrik/UnlockResourcePoller.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  jobs/BnRStatusPollerJob.js
  managers/BaseManager.js
  managers/backup-manager/DefaultBackupManager.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/eventmesh.ApiServerClient.spec.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/managers.DefaultBackupManager.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
  test/test_broker/watcher.ApiServerClientWatcher.spec.js
Labels: PipeLine:Green, SF2.0, unscheduled

#363 Fix lockedResourceDetails check
  broker/lib/fabrik/UnlockResourcePoller.js
Labels: unscheduled

#367 Add aborted state in poller
  broker/lib/fabrik/UnlockResourcePoller.js
Labels: unscheduled

#355 Deleting Transaction Logs after successful backup
  broker/config/settings.yml
  data-access-layer/iaas/BackupStore.js
  data-access-layer/iaas/CloudProviderClient.js
  jobs/ScheduleBackupJob.js
  test/test_broker/jobs.ScheduleBackupJob.spec.js
  test/test_broker/mocks/cloudProvider.js
Labels: Point In Time Recovery, unscheduled

#362 Remove sfv1 to sfv2.1 migration code
  api-controllers/ServiceFabrikApiController.js
  api-controllers/routes/broker/v2.js
  broker/lib/middleware.js
  common/utils/index.js
  jobs/BnRStatusPollerJob.js
  managers/backup-manager/BackupService.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/jobs.BnRStatusPollerJob.2.0.spec.js
  test/test_broker/managers.BackupService.spec.js
Labels: PipeLine:Green, SF2.0, unscheduled

#358 Cross Instance Point In Time Recovery support
  api-controllers/FabrikBaseController.js
  api-controllers/ServiceFabrikApiController.js
  broker/config/settings.yml
  broker/lib/fabrik/DirectorManager.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/utils.spec.js
Labels: DO NOT MERGE, Point In Time Recovery, unscheduled

#368 Changing the constant for the apiserver sync resource state timeout
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
Labels: unscheduled

#369 Test fix on master and change of constant
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
Labels: unscheduled

#354 Feature/uaa authentication
  broker/config/settings.yml
  common/HttpServer.js
  data-access-layer/bosh/BoshDirectorClient.js
  data-access-layer/cf/TokenIssuer.js
  data-access-layer/cf/UaaClient.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/cf.TokenIssuer.spec.js
  test/test_broker/cf.UaaClient.spec.js
Labels: DO NOT MERGE, unscheduled

#364 Introducing Lifecycle Managers (Bosh/Docker Managers)
  api-controllers/ServiceBrokerApiController.js
  api-controllers/ServiceFabrikApiController.js
  api-controllers/routes/broker/v2.js
  broker/config/certs/apiserver.crt
  broker/config/certs/apiserver.key
  broker/config/crds/bind.servicefabrik.io_v1alpha1_directorbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_dockerbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_virtualhostbinds.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_directors.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_dockers.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
  broker/config/settings.yml
  broker/config/templates/rabbitmq-manifest.yml.ejs
  broker/lib/fabrik/UnlockResourcePoller.js
  common/constants.js
  data-access-layer/eventmesh/ApiServerClient.js
  data-access-layer/service-agent/Agent.js
  managers/BaseDirectorService.js
  managers/BaseManager.js
  managers/BaseService.js
  managers/StartBoshManagers.js
  managers/StartDockerManagers.js
  managers/StartVirtualHostManagers.js
  managers/backup-manager/BackupService.js
  managers/backup-manager/DefaultBackupManager.js
  managers/bosh-manager/BoshBindManager.js
  managers/bosh-manager/BoshManager.js
  managers/bosh-manager/BoshTaskPoller.js
  managers/bosh-manager/DirectorService.js
  managers/bosh-manager/index.js
  managers/docker-manager/DockerBindManager.js
  managers/docker-manager/DockerImageLoaderService.js
  managers/docker-manager/DockerManager.js
  managers/docker-manager/DockerService.js
  managers/virtualhost-manager/VirtualHostAgent.js
  managers/virtualhost-manager/VirtualHostBindManager.js
  managers/virtualhost-manager/VirtualHostManager.js
  managers/virtualhost-manager/VirtualHostRelationMapper.js
  managers/virtualhost-manager/VirtualHostService.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-broker-api.catalog.spec.js
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  test/test_broker/acceptance/service-broker-api.instances.virtualHost.spec.js
  test/test_broker/acceptance/service-fabrik-admin.deployments.backups.director.spec.js
  test/test_broker/helper-files/apiserver-swagger.json
  test/test_broker/managers.BOSHManager.spec.js
  test/test_broker/managers.BackupService.spec.js
  test/test_broker/managers.DirectorService.ratelimits.spec.js
  test/test_broker/managers.DirectorService.spec.js
  test/test_broker/managers.DockerManager.spec.js
  test/test_broker/managers.DockerService.spec.js
  test/test_broker/managers.VirtualHostManager.spec.js
  test/test_broker/managers.VirtualHostService.spec.js
  test/test_broker/mocks/apiServerEventMesh.js
  test/test_broker/mocks/virtualHostAgent.js
Labels: PipeLine:Green, SF2.0, unscheduled

#370 Update README with steps to run managers
  README.md
Labels: unscheduled

#375 Adding component and TAM diagram
  img/SF2.0-component-quick-reference.png
  img/SF2.0-tam-block-diagram-overview.png
Labels: unscheduled

#371 Adding new sequence diagrams with SF2.0 changes
  architecture/SF2.0-basics.png
  architecture/SF2.0-service-binding-creation.png
  architecture/SF2.0-service-binding-deletion.png
  architecture/SF2.0-service-instance-bosh-backup-online.png
  architecture/SF2.0-service-instance-bosh-deprovisioning.png
  architecture/SF2.0-service-instance-bosh-provisioning.png
  architecture/SF2.0-service-instance-bosh-update-automated.png
  architecture/SF2.0-service-instance-bosh-update.png
  architecture/SF2.0-service-instance-docker-deprovisioning.png
  architecture/SF2.0-service-instance-docker-provisioning.png
  seqdiag.md
  src/architecture/SF2.0-basics.seq
  src/architecture/SF2.0-service-binding-creation.seq
  src/architecture/SF2.0-service-binding-deletion.seq
  src/architecture/SF2.0-service-instance-bosh-backup-online.seq
  src/architecture/SF2.0-service-instance-bosh-deprovisioning.seq
  src/architecture/SF2.0-service-instance-bosh-provisioning.seq
  src/architecture/SF2.0-service-instance-bosh-update-automated.seq
  src/architecture/SF2.0-service-instance-bosh-update.seq
  src/architecture/SF2.0-service-instance-docker-deprovisioning.seq
  src/architecture/SF2.0-service-instance-docker-provisioning.seq
Labels: unscheduled

#376 Fixing jshint error as js-beautify version is upgraded to 1.8.1
  data-access-layer/iaas/AzureClient.js
Labels: unscheduled

#377 Handle Migration for Docker Bind
  api-controllers/ServiceBrokerApiController.js
  data-access-layer/eventmesh/ApiServerClient.js
Labels: unscheduled

#372 Removing request.instance references
  api-controllers/ServiceBrokerApiController.js
  broker/lib/fabrik/BaseInstance.js
  broker/lib/fabrik/DirectorInstance.js
  broker/lib/fabrik/DockerInstance.js
  broker/lib/fabrik/VirtualHostInstance.js
  broker/lib/middleware.js
  test/test_broker/broker.middleware.spec.js
Labels: PipeLine:Green, SF2.0, unscheduled

#374 Improving reschedule backup logic to avoid cancelling schedule
  jobs/ScheduleBackupJob.js
  test/test_broker/jobs.ScheduleBackupJob.spec.js
Labels: Point In Time Recovery, unscheduled

#379 Fix getLastBackup
  api-controllers/ServiceFabrikApiController.js
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
Labels: unscheduled

#380 Adding Architecture details and capabilities of redesigned SF
  README.md
  SF2.0.md
Labels: unscheduled

#381 Sent event logs
  managers/restore-manager/RestoreTaskPoller.js
Labels: unscheduled

#382 Restore mgr fix rel.08b
  managers/restore-manager/RestoreTaskPoller.js
Labels: unscheduled
