Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2018-04, with the labels that each got.

#243 Fixes #190 : Delete OOB backups from BackupReaper
  lib/controllers/ServiceFabrikAdminController.js
  lib/fabrik/OobBackupManager.js
  lib/jobs/BackupReaperJob.js
  lib/jobs/ScheduledOobDeploymentBackupJob.js
  test/fabrik.OOBBackupManager.spec.js
  test/jobs.BackupReaperJobs.spec.js
  test/jobs.ScheduledOobDeploymentBackupJob.spec.js
  test/mocks/cloudProvider.js
Labels: unscheduled

#218 GCP B&R Support added
  config/settings.yml
  lib/iaas/AzureClient.js
  lib/iaas/BaseCloudClient.js
  lib/iaas/CloudProviderClient.js
  lib/iaas/GcpClient.js
  lib/iaas/index.js
  package.json
  test/iaas.GcpClient.spec.js
Labels: enhancement

#240 scheduler optimizations
  JobScheduler.js
  config/settings.yml
  lib/jobs/ScheduleManager.js
  lib/jobs/Scheduler.js
  lib/maintenance/MaintenanceManager.js
  test/JobScheduler.spec.js
  test/acceptance/service-fabrik-admin.instances.director.spec.js
  test/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/jobs.ScheduleManager.spec.js
  test/jobs.Scheduler.spec.js
  test/maintenance.MaintenanceManager.spec.js
Labels: RC:Sprint-3B, unscheduled

#249 Fix for #248: metadata file not deleted if backup data not found
  lib/iaas/AzureClient.js
  lib/iaas/BackupStore.js
  lib/iaas/CloudProviderClient.js
  lib/iaas/GcpClient.js
  test/jobs.ScheduledOobDeploymentBackupJob.spec.js
Labels: DO NOT MERGE, unscheduled

#250 Change truffleHog version to 2.0.89
  .travis.yml
Labels: unscheduled

#244 Fix for AWS RequestLimitExceeded issue
  config/settings.yml
  lib/constants.js
  lib/iaas/BackupStoreForServiceInstance.js
  lib/iaas/ComputeClient.js
  test/iaas.CloudProviderClient.js
Labels: unscheduled

#246 Feature/preupdate agent
  config/settings.yml
  config/templates/blueprint-manifest.yml.ejs
  lib/fabrik/Agent.js
  lib/fabrik/DirectorManager.js
  test/acceptance/service-broker-api.instances.director.spec.js
  test/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/fabrik.Agent.spec.js
  test/mocks/agent.js
Labels: DO NOT MERGE, unscheduled

#247 Add agent preupdate API documentation
  src/content/api/agent/v1.1/index.apib
  src/content/api/agent/v1.1/requests/lifecycle_preupdate.apib
  src/content/api/agent/v1.1/responses/lifecycle_preupdate_200.apib
  src/css/service-fabrik.css
Labels: DO NOT MERGE, unscheduled

#253 Enhance backup report
  lib/db/Repository.js
  lib/reports/BackupReportManager.js
  test/db.Repository.spec.js
  test/reports.BackupReportManager.spec.js
Labels: unscheduled

#254 changes to fix nocontainer issue related to docker & SF timeout issues
  lib/docker/DockerClient.js
  lib/fabrik/DockerInstance.js
  test/acceptance/service-broker-api.instances.docker.spec.js
  test/mocks/docker.js
Labels: unscheduled

#255 Fixes #248 Added more check for NotFound in lib/iaas/BaseCloudClient.js
  lib/docker/DockerClient.js
  lib/fabrik/DockerInstance.js
  lib/iaas/BaseCloudClient.js
  test/acceptance/service-broker-api.instances.docker.spec.js
  test/mocks/docker.js
Labels: unscheduled

#257 Fix getReportStartTime
  lib/reports/BackupReportManager.js
  test/reports.BackupReportManager.spec.js
Labels: unscheduled

#256 Fix getReportStartTime
  lib/reports/BackupReportManager.js
  test/reports.BackupReportManager.spec.js
Labels: unscheduled

#259 Change failed backup list
  lib/reports/BackupReportManager.js
  test/reports.BackupReportManager.spec.js
Labels: unscheduled

#258 Change failed backup list
  lib/reports/BackupReportManager.js
  test/reports.BackupReportManager.spec.js
Labels: unscheduled

#260 Add agent properties in preupdate request body
  lib/fabrik/DirectorManager.js
Labels: unscheduled

#261 Add agent properties in preupdate request body
  src/content/api/agent/v1.1/index.apib
  src/content/api/agent/v1.1/requests/lifecycle_preupdate.apib
Labels: unscheduled

#269 Fix/issue of multiple scheduler logs
  JobScheduler.js
  test/JobScheduler.spec.js
Labels: DO NOT MERGE, unscheduled
