Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2019-02, with the labels that each got.

#573 Restructuring travis job
  .codecov.yml
  .travis.yml
Labels: unscheduled

#563 Add utility functions for SSH, SSH keypair generation, disk, errand operations in BOSH Director interface
  common/errors.js
  common/utils/EncryptionManager.js
  common/utils/RsaKeyGenerator.js
  data-access-layer/bosh/BoshDirectorClient.js
  data-access-layer/bosh/BoshSshClient.js
  data-access-layer/iaas/AzureClient.js
  data-access-layer/iaas/GcpClient.js
  package.json
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/bosh.BoshSshClient.spec.js
  test/test_broker/iaas.AzureClient.spec.js
  test/test_broker/iaas.GcpClient.spec.js
  test/test_broker/utils.EncryptionManager.spec.js
  test/test_broker/utils.RsaKeyGenerator.spec.js
Labels: PipeLine:Green

#580 Make jshint version static
  package.json
Labels: unscheduled

#578 Fix: Unbind/delete failure leads to timeout of unbind/delete operation
  api-controllers/ServiceBrokerApiController.js
  broker/config/samples/templates/gotemplates/director/status.yaml
  broker/config/samples/templates/gotemplates/docker/status.yaml
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
Labels: unscheduled

#577 Fix: Unbind/delete failure leads to timeout of unbind/delete operation
  api-controllers/ServiceBrokerApiController.js
  broker/config/samples/templates/gotemplates/director/status.yaml
  broker/config/samples/templates/gotemplates/docker/status.yaml
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
Labels: PipeLine:Green, SF2.1, unscheduled

#581 [interoperator] Fix Tests
  interoperator/config/default/manager_image_patch.yaml
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
Labels: PipeLine:Green, unscheduled

#579 Disk Metadata fetch for Azure should expect disk name in BOSH CPI Format
  data-access-layer/iaas/AzureClient.js
  data-access-layer/iaas/CloudProviderClient.js
  test/test_broker/iaas.AzureClient.spec.js
  test/test_broker/iaas.CloudProviderClient.js
Labels: PipeLine:Green

#582 Add configurable indentity_provider
  broker/config/settings.yml
  data-access-layer/cf/UaaClient.js
Labels: PipeLine:yet-to-run, unscheduled

#587 Fail instance creation when SG Creation fails
  common/constants.js
  operators/bosh-operator/DirectorService.js
  platform-managers/CfPlatformManager.js
  test/test_broker/mocks/cloudController.js
  test/test_broker/operators.DirectorService.spec.js
Labels: unscheduled

#583 Cleanup changes : Details in the comment
  api-controllers/ServiceBrokerApiController.js
  broker/lib/index.js
  broker/server.js
  common/constants.js
  common/models/Plan.js
  common/utils/index.js
  operators/StartDockerOperators.js
  platform-managers/CfPlatformManager.js
Labels: PipeLine:Green, unscheduled

#585 Make hostname in the docker credentials mandatory
  operators/docker-operator/DockerService.js
Labels: PipeLine:Green, unscheduled

#576 Inter-operator architecture documentation in gh-pages branch.
  inter-operator/Makefile
  inter-operator/architecture/basic.md
  inter-operator/architecture/diagrams.pptx
  inter-operator/architecture/images/basic-control-flow-bind.png
  inter-operator/architecture/images/basic-control-flow-catalog.png
  inter-operator/architecture/images/basic-control-flow-last-operation.png
  inter-operator/architecture/images/basic-control-flow-provision.png
  inter-operator/architecture/images/inter-operator.png
  inter-operator/architecture/~$diagrams.pptx
Labels: unscheduled

#591 Fixing get deployment summary API
  api-controllers/ServiceFabrikAdminController.js
Labels: unscheduled

#589 Define error codes
  common/constants.js
  common/errors.js
  common/utils/index.js
  data-access-layer/bosh/BoshDirectorClient.js
  data-access-layer/docker/Docker.js
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  operators/bosh-operator/BoshOperator.js
  operators/bosh-operator/BoshTaskStatusPoller.js
  operators/bosh-operator/DirectorService.js
  platform-managers/CfPlatformManager.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/errors.spec.js
  test/test_broker/operators.DirectorService.ratelimits.spec.js
Labels: PipeLine:Green

#588 Fixing deletion of snapshot
  data-access-layer/iaas/BackupStore.js
Labels: unscheduled

#590 [interoperator] Update kubebuilder, Update states
  interoperator/Dockerfile
  interoperator/Gopkg.lock
  interoperator/Gopkg.toml
  interoperator/Makefile
  interoperator/cmd/manager/main.go
  interoperator/config/crds/osb_v1alpha1_sfplan.yaml
  interoperator/config/crds/osb_v1alpha1_sfservice.yaml
  interoperator/config/crds/osb_v1alpha1_sfservicebinding.yaml
  interoperator/config/crds/osb_v1alpha1_sfserviceinstance.yaml
  interoperator/config/default/kustomization.yaml
  interoperator/config/default/manager_auth_proxy_patch.yaml
  interoperator/config/default/manager_prometheus_metrics_patch.yaml
  interoperator/config/manager/manager.yaml
  interoperator/config/rbac/auth_proxy_role.yaml
  interoperator/config/rbac/auth_proxy_role_binding.yaml
  interoperator/config/rbac/auth_proxy_service.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/apis/osb/v1alpha1/v1alpha1_suite_test.go
  interoperator/pkg/controller/controller_test.go
  interoperator/pkg/controller/sfplan/sfplan_controller.go
  interoperator/pkg/controller/sfplan/sfplan_controller_suite_test.go
  interoperator/pkg/controller/sfservice/sfservice_controller.go
  interoperator/pkg/controller/sfservice/sfservice_controller_suite_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_suite_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_suite_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/cluster/factory/factory.go
  interoperator/pkg/internal/cluster/factory/factory_suite_test.go
  interoperator/pkg/internal/resources/mock_resources/mock_resources.go
  interoperator/pkg/internal/resources/resources.go
  interoperator/pkg/internal/resources/resources_test.go
Labels: PipeLine:Green, unscheduled

#593 Rel 2019.t01a hotfix
  api-controllers/ServiceFabrikAdminController.js
  interoperator/Dockerfile
  interoperator/Gopkg.lock
  interoperator/Gopkg.toml
  interoperator/Makefile
  interoperator/cmd/manager/main.go
  interoperator/config/crds/osb_v1alpha1_sfplan.yaml
  interoperator/config/crds/osb_v1alpha1_sfservice.yaml
  interoperator/config/crds/osb_v1alpha1_sfservicebinding.yaml
  interoperator/config/crds/osb_v1alpha1_sfserviceinstance.yaml
  interoperator/config/default/kustomization.yaml
  interoperator/config/default/manager_auth_proxy_patch.yaml
  interoperator/config/default/manager_image_patch.yaml
  interoperator/config/default/manager_prometheus_metrics_patch.yaml
  interoperator/config/manager/manager.yaml
  interoperator/config/rbac/auth_proxy_role.yaml
  interoperator/config/rbac/auth_proxy_role_binding.yaml
  interoperator/config/rbac/auth_proxy_service.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/apis/osb/v1alpha1/v1alpha1_suite_test.go
  interoperator/pkg/controller/controller_test.go
  interoperator/pkg/controller/sfplan/sfplan_controller.go
  interoperator/pkg/controller/sfplan/sfplan_controller_suite_test.go
  interoperator/pkg/controller/sfservice/sfservice_controller.go
  interoperator/pkg/controller/sfservice/sfservice_controller_suite_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_suite_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_suite_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/cluster/factory/factory.go
  interoperator/pkg/internal/cluster/factory/factory_suite_test.go
  interoperator/pkg/internal/resources/mock_resources/mock_resources.go
  interoperator/pkg/internal/resources/resources.go
  interoperator/pkg/internal/resources/resources_test.go
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
Labels: unscheduled

#592 Webhook for setting state label modified
  webhooks/pkg/webhooks/manager/webhook.go
  webhooks/pkg/webhooks/manager/webhook_test.go
Labels: PipeLine:Green, unscheduled

#594 Adding placeholders for instance sharing related functions in K8sPlatformManager
  platform-managers/K8sPlatformManager.js
  test/test_broker/operators.DirectorService.spec.js
  test/test_broker/operators.DockerService.spec.js
Labels: unscheduled

#596 [interoperator] Right to left update only when in progress
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
Labels: unscheduled

#595 Allows for clients to customize dashboard URL
  api-controllers/ServiceBrokerApiController.js
  broker/config/settings.yml
  common/constants.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#598 Uncomment the mocks verify check
  jobs/MeterInstanceJob.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
  test/test_broker/mocks/index.js
  test/test_broker/operators.DirectorService.spec.js
Labels: unscheduled

#584 fix Rsyslog-Error 2077
  common/logger.js
Labels: unscheduled

#599 Add admin endpoint to trigger job
  .eslintignore
  .gitignore
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/routes/admin.js
  broker/bin/broker
  jobs/MeterInstanceJob.js
  jobs/ScheduleManager.js
  test/test_broker/acceptance/service-fabrik-admin.updates.spec.js
  test/test_broker/jobs.MeteringInstanceJobs.spec.js
  test/test_broker/jobs.ScheduleManager.spec.js
  webhooks/Makefile
  webhooks/pkg/webhooks/manager/main.go
  webhooks/pkg/webhooks/manager/webhook.go
Labels: unscheduled

#600 [interoperator] Improve logging
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/internal/resources/resources.go
Labels: PipeLine:Green, unscheduled

#601 Improve eventlogs generated for metering
  common/constants.js
  common/utils/EventLogRiemannClient.js
  jobs/MeterInstanceJob.js
  test/test_broker/jobs.MeteringInstanceJobs.spec.js
Labels: PipeLine:yet-to-run, unscheduled

#602 [interoperator] Update templates
  broker/config/samples/templates/gotemplates/director/bind.yaml
  broker/config/samples/templates/gotemplates/director/provision.yaml
  broker/config/samples/templates/gotemplates/docker/bind.yaml
  broker/config/samples/templates/gotemplates/docker/provision.yaml
Labels: unscheduled
