Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2019-09, with the labels that each got.

#688 [interoperator] SFService replicator watch
  interoperator/pkg/controller/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller.go
Labels: unscheduled

#689 Refactoring provisioner controller
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
Labels: unscheduled

#692 Add mock_provisioner to Ignore lists
  .codecov.yml
  .gitattributes
Labels: unscheduled

#693 Add UTs for provisioner
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller_suite_test.go
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller_test.go
Labels: unscheduled

#695 Add expects
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller_test.go
Labels: unscheduled

#694 UTs for binding replicator
  interoperator/pkg/controller/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller.go
  interoperator/pkg/controller/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller_suite_test.go
  interoperator/pkg/controller/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller_test.go
Labels: unscheduled

#696 Fix provisioner review comments
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/pkg/internal/provisioner/mock_provisioner/mock_provisioner.go
  interoperator/pkg/internal/provisioner/provisioner.go
  interoperator/pkg/internal/provisioner/provisioner_test.go
Labels: unscheduled

#676 Add schema validation for service instance operation via ajv
  api-controllers/routes/broker/v2.js
  broker/config/settings.yml
  broker/lib/middleware.js
  common/errors.js
  package.json
  test/test_broker/acceptance/service-broker-api.instances.director.spec.js
Labels: unscheduled

#699 Adding multi-cluster support documentation
  inter-operator/architecture/basic.md
  inter-operator/architecture/images/Deployment Flow Updated.png
  inter-operator/architecture/images/Deployment Flow.png
  inter-operator/architecture/images/Runtime Flow Updated.png
  inter-operator/architecture/images/Runtime Flow.png
Labels: unscheduled

#704 Adding interoperator helm chart package
  helm-charts/README.md
  helm-charts/index.yaml
  helm-charts/interoperator-0.3.0.tgz
  helm-charts/interoperator-0.4.0.tgz
  helm-charts/sources/interoperator/.helmignore
  helm-charts/sources/interoperator/Chart.yaml
  helm-charts/sources/interoperator/conf/settings.yaml
  helm-charts/sources/interoperator/templates/broker.yaml
  helm-charts/sources/interoperator/templates/interoperator_config.yaml
  helm-charts/sources/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/sources/interoperator/templates/provisioner.yaml
  helm-charts/sources/interoperator/templates/rbac_role_binding.yaml
  helm-charts/sources/interoperator/templates/scheduler.yaml
  helm-charts/sources/interoperator/templates/settings.yaml
  helm-charts/sources/interoperator/templates/sfcluster.yaml
  helm-charts/sources/interoperator/templates/sfplan.yaml
  helm-charts/sources/interoperator/templates/sfservice.yaml
  helm-charts/sources/interoperator/templates/sfservicebinding.yaml
  helm-charts/sources/interoperator/templates/sfserviceinstance.yaml
  helm-charts/sources/interoperator/values.yaml
Labels: unscheduled

#707 Remove Helm chart from Gh-pages
  helm-charts/README.md
  helm-charts/sources/interoperator/.helmignore
  helm-charts/sources/interoperator/Chart.yaml
  helm-charts/sources/interoperator/conf/settings.yaml
  helm-charts/sources/interoperator/templates/broker.yaml
  helm-charts/sources/interoperator/templates/interoperator_config.yaml
  helm-charts/sources/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/sources/interoperator/templates/provisioner.yaml
  helm-charts/sources/interoperator/templates/rbac_role_binding.yaml
  helm-charts/sources/interoperator/templates/scheduler.yaml
  helm-charts/sources/interoperator/templates/settings.yaml
  helm-charts/sources/interoperator/templates/sfcluster.yaml
  helm-charts/sources/interoperator/templates/sfplan.yaml
  helm-charts/sources/interoperator/templates/sfservice.yaml
  helm-charts/sources/interoperator/templates/sfservicebinding.yaml
  helm-charts/sources/interoperator/templates/sfserviceinstance.yaml
  helm-charts/sources/interoperator/values.yaml
Labels: unscheduled

#706 Add Helm chart to source code
  helm-charts/interoperator/.helmignore
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/interoperator_config.yaml
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/rbac_role_binding.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  helm-charts/interoperator/templates/settings.yaml
  helm-charts/interoperator/templates/sfcluster.yaml
  helm-charts/interoperator/templates/sfplan.yaml
  helm-charts/interoperator/templates/sfservice.yaml
  helm-charts/interoperator/templates/sfservicebinding.yaml
  helm-charts/interoperator/templates/sfserviceinstance.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#708 Modifying getDeploymentSummary to use ApiServer
  api-controllers/ServiceFabrikAdminController.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
Labels: unscheduled

#710 Update helm chart 0.4.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.4.0.tgz
Labels: unscheduled

#709 Update Helm chart
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#711 Add limitations for multi-cluster concept
  inter-operator/architecture/basic.md
Labels: unscheduled

#675 [interoperator] AdditionalPrinterColumns
  interoperator/config/crds/osb_v1alpha1_sfservicebinding.yaml
  interoperator/config/crds/osb_v1alpha1_sfserviceinstance.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
Labels: unscheduled

#712 Handle space not existing scenario
  api-controllers/ServiceFabrikAdminController.js
Labels: unscheduled

#713 [Rel branch] handle space not existing scenario
  api-controllers/ServiceFabrikAdminController.js
Labels: unscheduled

#714 [interoperator] Fix bug in mcd provisoner
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
Labels: unscheduled

#703 [Interoperator] Enabling liveness and readiness probe
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  interoperator/cmd/manager/main.go
Labels: PipeLine:Green, unscheduled

#687 makefile: fix dependency path
  webhooks/Makefile
Labels: unscheduled

#716 Removing unused crds from settings of helm chart
  common/UnlockResourcePoller.js
  data-access-layer/eventmesh/ApiServerClient.js
  helm-charts/interoperator/conf/settings.yaml
Labels: PipeLine:yet-to-run, unscheduled

#722 Making broker user and pass flexible
  common/config.js
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/values.yaml
Labels: PipeLine:Green, unscheduled

#721 [interoperator] Least Utilized Scheduler
  helm-charts/interoperator/templates/sfcluster.yaml
  helm-charts/interoperator/templates/sfservicebinding.yaml
  helm-charts/interoperator/templates/sfserviceinstance.yaml
  helm-charts/interoperator/values.yaml
  interoperator/Makefile
  interoperator/README.md
  interoperator/pkg/constants/constants.go
  interoperator/pkg/controller/add_schedulers.go
  interoperator/pkg/controller/schedulers/add_sfdefaultscheduler.go
  interoperator/pkg/controller/schedulers/add_sfleastutilizedscheduler.go
  interoperator/pkg/controller/schedulers/add_sfroundrobinscheduler.go
  interoperator/pkg/controller/schedulers/schedulers.go
  interoperator/pkg/controller/schedulers/sfleastutilizedscheduler/sfleastutilizedscheduler_controller.go
  interoperator/pkg/controller/schedulers/sfleastutilizedscheduler/sfleastutilizedscheduler_controller_suite_test.go
  interoperator/pkg/controller/schedulers/sfleastutilizedscheduler/sfleastutilizedscheduler_controller_test.go
  interoperator/pkg/controller/schedulers/sfroundrobinscheduler/sfroundrobinscheduler_controller.go
Labels: unscheduled

#725 Removing broker username and password from the setting.yml
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#729 Revert "Removing broker username and password from the setting.yml"
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#732 Updating broker/Interoperator docker image versions
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#733 Adding Helm Chart Package: 0.4.1
  helm-charts/index.yaml
  helm-charts/interoperator-0.4.1.tgz
Labels: unscheduled
