Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2019-01, with the labels that each got.

#521 Adding extra field in deployment CRDs to keep track of current state in case of failure scenarios
  api-controllers/DashboardController.js
  api-controllers/ServiceBrokerApiController.js
  api-controllers/ServiceFabrikAdminController.js
  api-controllers/ServiceFabrikApiController.js
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_directors.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_dockers.yaml
  jobs/ServiceInstanceUpdateJob.js
  operators/bosh-operator/BoshTaskStatusPoller.js
  operators/docker-operator/DockerOperator.js
  test/test_broker/acceptance/dashboard.director.spec.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
  test/test_broker/cf.TokenIssuer.spec.js
  test/test_broker/jobs.ServiceInstanceUpdateJob.spec.js
  test/test_broker/mocks/uaa.js
Labels: PipeLine:Green, unscheduled

#528 Enable service instance sharing via Service Fabrik
  broker/config/settings.yml
  common/errors.js
  operators/bosh-operator/DirectorService.js
  platform-managers/BasePlatformManager.js
  platform-managers/CfPlatformManager.js
  test/test_broker/fabrik.CfPlatformManager.spec.js
  test/test_broker/mocks/cloudController.js
  test/test_broker/operators.DirectorService.spec.js
Labels: PipeLine:Green, unscheduled

#538 [interoperator] Add previous values to SfServiceInstance
  interoperator/config/crds/osb_v1alpha1_sfserviceinstance.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#537 Changes for returning complete catalog with /sm/v2/catalog endpoint
  platform-managers/BasePlatformManager.js
  test/test_broker/acceptance/service-broker-api.catalog.spec.js
Labels: unscheduled

#539 Initial travis change
  .travis.yml
  interoperator/pkg/apis/osb/v1alpha1/sfplan_types_test.go
  interoperator/scripts/install.sh
  interoperator/scripts/install_test.sh
Labels: unscheduled

#541 [interoperator] Add test for sfplan
  interoperator/pkg/apis/osb/v1alpha1/sfplan_types_test.go
Labels: unscheduled

#542 [interoperator] Testcases for deepcopy
  interoperator/config/crds/osb_v1alpha1_sfplan.yaml
  interoperator/config/crds/osb_v1alpha1_sfservice.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfplan_types_test.go
  interoperator/pkg/apis/osb/v1alpha1/sfservice_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfservice_types_test.go
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types_test.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types_test.go
  interoperator/pkg/apis/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/pkg/internal/renderer/factory/gotemplaterenderer_test.go
  interoperator/pkg/internal/renderer/gotemplate/functions_test.go
Labels: unscheduled

#535 Removing CF CC dependencies in extension APIs code flow except authentication and authorization
  api-controllers/ServiceFabrikApiController.js
  common/utils/index.js
  jobs/BackupReaperJob.js
  jobs/ScheduleBackupJob.js
  operators/BaseService.js
  test/test_broker/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/jobs.BackupReaperJobs.spec.js
  test/test_broker/jobs.ScheduleBackupJob.spec.js
  test/test_broker/utils.spec.js
Labels: DO NOT MERGE, PipeLine:Green, unscheduled

#545 [interoperator] Test cases for service/plan controller
  .travis.yml
  interoperator/pkg/controller/sfplan/sfplan_controller.go
  interoperator/pkg/controller/sfplan/sfplan_controller_test.go
  interoperator/pkg/controller/sfservice/sfservice_controller.go
  interoperator/pkg/controller/sfservice/sfservice_controller_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
Labels: unscheduled

#546 [interoperator] Add contentBase64 field in templateSpec
  broker/config/settings.yml
  interoperator/config/crds/osb_v1alpha1_sfplan.yaml
  interoperator/config/rbac/rbac_role.yaml
  interoperator/pkg/apis/osb/v1alpha1/sfplan_types.go
  interoperator/pkg/internal/renderer/factory/factory.go
  interoperator/pkg/internal/renderer/factory/gotemplaterenderer_test.go
  interoperator/pkg/internal/renderer/gotemplate/renderer.go
Labels: unscheduled

#548 [interoperator] Avoid suppressing of error
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#547 Upgrade of deprecated libraries
  package.json
  test/test_broker/iaas.AzureClient.spec.js
Labels: PipeLine:Green, unscheduled

#549 Feature/inter operator
  interoperator/pkg/controller/controller_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/resources/resources.go
  interoperator/pkg/webhook/webhook_test.go
Labels: unscheduled

#551 [interoperator] Testcases for Instance Controller
  interoperator/Gopkg.lock
  interoperator/Gopkg.toml
  interoperator/pkg/controller/sfplan/sfplan_controller_test.go
  interoperator/pkg/controller/sfservice/sfservice_controller_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/cluster/factory/factory.go
  interoperator/pkg/internal/cluster/factory/factory_test.go
  interoperator/pkg/internal/cluster/factory/mock_factory/mock_factory.go
  interoperator/pkg/internal/resources/mock_resources/mock_resources.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#555 [interoperator] Delete bind secret on unbind
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
Labels: unscheduled

#557 [interoperator] Update reconcile
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#558 Revert "[interoperator] Update reconcile"
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#552 Cancel schedule update API
  api-controllers/ServiceFabrikApiController.js
  api-controllers/routes/api/v1.js
  common/config/eventlog-config-external.yml
  jobs/ScheduleManager.js
  jobs/Scheduler.js
  test/test_broker/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  test/test_broker/acceptance/service-fabrik-api.instances.director.spec.js
  test/test_broker/jobs.ScheduleManager.spec.js
  test/test_broker/jobs.Scheduler.spec.js
Labels: PipeLine:Green

#553 Cancel Scheduled Updates API Doc Changes
  api/broker_v1.0.html
  src/content/api/broker/v1.0/index.apib
Labels: PipeLine:Green

#562 Minor Fixes for SF2.1
  api-controllers/ServiceBrokerApiController.js
  broker/config/samples/templates/gotemplates/director/bind.yaml
  broker/config/samples/templates/gotemplates/director/status.yaml
  broker/config/samples/templates/gotemplates/docker/bind.yaml
  broker/config/samples/templates/gotemplates/docker/status.yaml
  data-access-layer/eventmesh/ApiServerClient.js
  interoperator/Dockerfile
  interoperator/pkg/controller/sfplan/sfplan_controller_test.go
  interoperator/pkg/controller/sfservice/sfservice_controller_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/resources/resources.go
Labels: unscheduled

#564 Define multi az downgrade service flow definition
  common/constants.js
  common/utils/ServiceFlowMapper.js
  operators/serviceflow-operator/serial-serviceflow-definition.yml
  test/test_broker/utils.ServiceflowMapper.js
Labels: PipeLine:Green, unscheduled

#565 Fixing json-fying of response
  api-controllers/ServiceFabrikAdminController.js
  test/test_broker/acceptance/service-fabrik-admin.updates.spec.js
Labels: unscheduled

#560 Bumping version of pkgcloud and some other modules
  data-access-layer/iaas/CloudProviderClient.js
  package.json
Labels: PipeLine:Green, unscheduled

#566 LastOperation is removed from CRDs per SF2.1 changes.
  api-controllers/ServiceBrokerApiController.js
  broker/config/crds/serviceflow.servicefabrik.io_v1alpha1_serialserviceflows.yaml
  broker/config/crds/serviceflow.servicefabrik.io_v1alpha1_tasks.yaml
  operators/serviceflow-operator/SerialServiceFlowOperator.js
  operators/serviceflow-operator/task/ServiceInstanceUpdateTask.js
  operators/serviceflow-operator/task/Task.js
  operators/serviceflow-operator/task/TaskOperator.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
  test/test_broker/operators.serviceflow.SerialServiceFlow.spec.js
  test/test_broker/operators.serviceflow.tasks.ServiceInstanceUpdateTask.spec.js
  test/test_broker/operators.serviceflow.tasks.Task.spec.js
Labels: PipeLine:Green, unscheduled

#569 Update README.md : Adding go report card and codecov badges
  README.md
Labels: unscheduled

#570 Enable sharing instances of Docker dev plans as well
  operators/docker-operator/DockerService.js
  test/test_broker/operators.DockerService.spec.js
Labels: PipeLine:Green
