Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2019-04, with the labels that each got.

#610 Using dummy context while computing outdated deployments
  api-controllers/ServiceFabrikAdminController.js
  common/constants.js
  common/utils/index.js
  test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
  test/test_broker/utils.spec.js
Labels: PipeLine:Green

#619 [interoperator] Error handling
  interoperator/pkg/apis/osb/v1alpha1/sfplan_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types_test.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/errors/code.go
  interoperator/pkg/errors/errors.go
  interoperator/pkg/errors/errors_test.go
  interoperator/pkg/internal/cluster/factory/factory.go
  interoperator/pkg/internal/dynamic/dynamic.go
  interoperator/pkg/internal/properties/properties.go
  interoperator/pkg/internal/renderer/factory/helmtemplaterenderer_test.go
  interoperator/pkg/internal/renderer/gotemplate/renderer.go
  interoperator/pkg/internal/renderer/helm/renderer.go
  interoperator/pkg/internal/resources/resources.go
  interoperator/pkg/internal/resources/resources_test.go
  interoperator/pkg/internal/services/services.go
  interoperator/pkg/internal/services/services_test.go
  interoperator/pkg/webhook/webhook_test.go
Labels: PipeLine:Green, unscheduled

#620 Adding 'timeBased=true' query paramater to metering URL
  data-access-layer/metering/MeteringClient.js
  test/test_broker/mocks/metering.js
Labels: PipeLine:Green, unscheduled

#623 Fixing Ali Cloud download blob method
  data-access-layer/iaas/AliClient.js
Labels: unscheduled

#624 Keep only organization_guid and space_guid in manifest tags
  operators/bosh-operator/DirectorService.js
Labels: unscheduled

#628 Interoperator cf consumption
  broker/lib/middleware.js
  common/utils/index.js
  data-access-layer/cf/index.js
  package.json
  quota/QuotaManager.js
  test/test_broker/broker.middleware.spec.js
Labels: PipeLine:Green, unscheduled

#625 Adding schedule backup call after successful BoshBasedRestore for pitr enabled services
  operators/BaseDirectorService.js
  operators/bosh-restore-operator/BoshRestoreService.js
  operators/restore-operator/RestoreService.js
  test/test_broker/operators.BoshRestoreService.spec.js
Labels: PipeLine:Green

#629 Returning dashboardUrl only if external endpoint attributes are set
  api-controllers/ServiceBrokerApiController.js
Labels: PipeLine:Green, unscheduled

#630 Add Aliclient support for BoshRestore and Delete Snapshot
  common/constants.js
  data-access-layer/iaas/AliClient.js
  data-access-layer/iaas/BaseCloudClient.js
  test/test_broker/iaas.AliClient.spec.js
Labels: PipeLine:Green, unscheduled

#631 Add default ecs endpoint aliclient
  common/constants.js
  data-access-layer/iaas/AliClient.js
  test/test_broker/iaas.AliClient.spec.js
Labels: unscheduled

#621 Adding default eventName for update events
  common/EventLogInterceptor.js
  common/constants.js
Labels: PipeLine:Green, unscheduled
