Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2019-08, with the labels that each got.

#665 Removing bosh property related operations from codebase
  data-access-layer/bosh/BoshDirectorClient.js
  data-access-layer/db/DBManager/DBManager.js
  operators/bosh-operator/DirectorService.js
  operators/virtualhost-operator/VirtualHostService.js
  test/test_broker/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  test/test_broker/bosh.BoshDirectorClient.spec.js
  test/test_broker/fabrik.DBManager.spec.js
  test/test_broker/mocks/director.js
  test/test_broker/operators.DirectorService.spec.js
  test/test_broker/operators.VirtualHostService.spec.js
Labels: PipeLine:Green, unscheduled

#669 [interoperator] Fix crash
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
Labels: unscheduled

#671 [Release branch] Introducing separate error for ApiServer page not found
  common/errors.js
  data-access-layer/db/DBManager/DBManager.js
  data-access-layer/eventmesh/ApiServerClient.js
Labels: unscheduled

#670 [Potential test cycle fix]introducing separate error for ApiServer page not found
  common/errors.js
  data-access-layer/db/DBManager/DBManager.js
  data-access-layer/eventmesh/ApiServerClient.js
Labels: DO NOT MERGE, unscheduled

#672 Adding a safety check for cron expressions
  common/utils/index.js
  jobs/ScheduleManager.js
Labels: DO NOT MERGE, unscheduled

#674 Modify runNow API to schedule the job after one minute
  api-controllers/ServiceFabrikAdminController.js
  common/utils/index.js
  test/test_broker/acceptance/service-fabrik-admin.updates.spec.js
Labels: unscheduled

#677 Feature/mcd
  interoperator/Makefile
  interoperator/pkg/constants/constants.go
  interoperator/pkg/controller/add_mcd_provisoner.go
  interoperator/pkg/controller/multiclusterdeploy/provisioner_controller.go
  interoperator/pkg/internal/provisioner/provisioner.go
Labels: unscheduled

#678 Add Provisioner + Role
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
Labels: unscheduled

#679 Adding sfservices and sfplans replicator
  interoperator/pkg/controller/multiclusterdeploy/add_mcd_sfservices.go
  interoperator/pkg/controller/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller.go
Labels: unscheduled

#682 Add create/update ns for provisioner deployer
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/pkg/internal/provisioner/mock_provisioner/mock_provisioner.go
  interoperator/pkg/internal/provisioner/provisioner.go
  interoperator/pkg/internal/provisioner/provisioner_test.go
Labels: unscheduled

#681 [interoperator] Generate Client of osb resources
  interoperator/README.md
  interoperator/pkg/client/clientset/versioned/clientset.go
  interoperator/pkg/client/clientset/versioned/doc.go
  interoperator/pkg/client/clientset/versioned/fake/clientset_generated.go
  interoperator/pkg/client/clientset/versioned/fake/doc.go
  interoperator/pkg/client/clientset/versioned/fake/register.go
  interoperator/pkg/client/clientset/versioned/scheme/doc.go
  interoperator/pkg/client/clientset/versioned/scheme/register.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/doc.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/doc.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_osb_client.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfplan.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfservice.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfservicebinding.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfserviceinstance.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/generated_expansion.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/osb_client.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfplan.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfservice.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfservicebinding.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfserviceinstance.go
Labels: unscheduled

#683 [interoperator] Mulicluster Watch
  interoperator/cmd/manager/main.go
  interoperator/pkg/constants/constants.go
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/pkg/controller/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/pkg/controller/multiclusterdeploy/watchmanager/clusterwatcher.go
  interoperator/pkg/controller/multiclusterdeploy/watchmanager/internal.go
  interoperator/pkg/controller/multiclusterdeploy/watchmanager/manager.go
  interoperator/pkg/controller/multiclusterdeploy/watchmanager/manager_default.go
  interoperator/pkg/errors/code.go
  interoperator/pkg/errors/errors.go
Labels: unscheduled

#685 Edit Dockerfile
  interoperator/Dockerfile
  interoperator/pkg/constants/constants.go
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/pkg/internal/config/config.go
Labels: unscheduled

#684 Bind replication
  interoperator/pkg/controller/multiclusterdeploy/add_sfservicebindingreplicator.go
  interoperator/pkg/controller/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller.go
Labels: in progress, unscheduled

#686 Register CRDs in target clusters
  interoperator/pkg/controller/multiclusterdeploy/provisioner/provisioner_controller.go
Labels: unscheduled
