Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2019-07, with the labels that each got.

#652 Adding custom tags for deployments
  common/models/Service.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/models.Service.spec.js
Labels: PipeLine:Green, unscheduled

#651 Making scheduler and instance controller serial
  interoperator/pkg/controller/sfdefaultscheduler/sfdefaultscheduler_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
Labels: unscheduled

#653 Adding env by default while enriching the metering crd
  jobs/MeterInstanceJob.js
  test/test_broker/jobs.MeteringInstanceJobs.spec.js
Labels: unscheduled

#654 Fix getDbBindInfo method: Throw NotFound if binding is not present
  data-access-layer/db/DBManager/DBManager.js
Labels: unscheduled

#650 Add option to disable Riemann event logging
  common/utils/index.js
Labels: unscheduled

#648 Introducing Status Pollers for Bosh Based Restore
  common/constants.js
  operators/StartBackupRestoreOperators.js
  operators/bosh-restore-operator/BoshRestoreService.js
  operators/bosh-restore-operator/BoshRestoreStatusPoller.js
  operators/bosh-restore-operator/DefaultBoshRestoreOperator.js
  test/test_broker/operators.BoshRestoreService.spec.js
  test/test_broker/operators.BoshRestoreStatusPoller.spec.js
Labels: DO NOT MERGE, PipeLine:Green, unscheduled

#646 [interoperator] Cluster Registry
  interoperator/Gopkg.lock
  interoperator/config/crds/osb_v1alpha1_sfservicebinding.yaml
  interoperator/config/crds/osb_v1alpha1_sfserviceinstance.yaml
  interoperator/config/crds/resource_v1alpha1_sfcluster.yaml
  interoperator/config/samples/resource_v1alpha1_sfcluster.yaml
  interoperator/pkg/apis/addtoscheme_resource_v1alpha1.go
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/apis/resource/group.go
  interoperator/pkg/apis/resource/v1alpha1/doc.go
  interoperator/pkg/apis/resource/v1alpha1/register.go
  interoperator/pkg/apis/resource/v1alpha1/sfcluster_types.go
  interoperator/pkg/apis/resource/v1alpha1/sfcluster_types_test.go
  interoperator/pkg/apis/resource/v1alpha1/v1alpha1_suite_test.go
  interoperator/pkg/apis/resource/v1alpha1/zz_generated.deepcopy.go
  interoperator/pkg/cluster/cluster.go
  interoperator/pkg/cluster/registry/mock_registry/mock_registry.go
  interoperator/pkg/cluster/registry/registry.go
  interoperator/pkg/cluster/registry/registry_suite_test.go
  interoperator/pkg/cluster/registry/registry_test.go
  interoperator/pkg/controller/sfdefaultscheduler/sfdefaultscheduler_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/errors/code.go
  interoperator/pkg/errors/errors.go
  interoperator/pkg/errors/errors_test.go
  interoperator/pkg/internal/cluster/factory/factory.go
  interoperator/pkg/internal/cluster/factory/factory_test.go
  interoperator/pkg/internal/cluster/factory/mock_factory/mock_factory.go
Labels: DO NOT MERGE, unscheduled

#657 Removing empty dashboard client as defaults
  common/models/Service.js
  test/test_broker/models.Service.spec.js
Labels: unscheduled

#658 Assigning dashboard client as reference
  interoperator/pkg/apis/osb/v1alpha1/sfservice_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfservice_types_test.go
  interoperator/pkg/apis/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/pkg/controller/sfplan/sfplan_controller_test.go
  interoperator/pkg/controller/sfservice/sfservice_controller_test.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/pkg/internal/resources/resources_test.go
  interoperator/pkg/internal/services/services_test.go
  interoperator/pkg/watches/watches_test.go
Labels: PipeLine:Green, unscheduled

#655 Add post processing polling to bosh manager
  common/constants.js
  data-access-layer/service-agent/Agent.js
  operators/StartBoshOperators.js
  operators/bosh-operator/BoshPostProcessingPoller.js
  operators/bosh-operator/BoshTaskStatusPoller.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/mocks/agent.js
  test/test_broker/operators.BoshPostProcessingPoller.spec.js
  test/test_broker/operators.DirectorService.spec.js
Labels: PipeLine:Green, unscheduled

#656 Add post processing routes to the agent api
  src/content/api/agent/v1.1/index.apib
  src/content/api/agent/v1.1/responses/lifecyle_async_polling_200.apib
Labels: unscheduled

#661 [interoperator] Bind timeout during watch refresh
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/errors/code.go
  interoperator/pkg/errors/errors.go
Labels: unscheduled

#660 [interoperator] Bind timeout during watch refresh
  interoperator/pkg/apis/osb/v1alpha1/sfservicebinding_types.go
  interoperator/pkg/apis/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/pkg/controller/sfservicebinding/sfservicebinding_controller.go
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/pkg/errors/code.go
  interoperator/pkg/errors/errors.go
Labels: unscheduled

#664 [interoperator] Provision timeout during startup
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
Labels: unscheduled

#662 [interoperator] Provision timeout during startup
  interoperator/pkg/controller/sfserviceinstance/sfserviceinstance_controller.go
Labels: unscheduled
