Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-06, with the labels that each got.

#845 Update Readme to run locally
  README.md
  interoperator/Makefile
Labels: unscheduled

#846 Separating out admin process from broker
  broker/applications/admin/.eslintignore
  broker/applications/admin/.eslintrc.json
  broker/applications/admin/.prettierrc
  broker/applications/admin/index.js
  broker/applications/admin/package.json
  broker/applications/admin/src/admin.js
  broker/applications/admin/src/api-controllers/ServiceFabrikAdminController.js
  broker/applications/admin/src/api-controllers/index.js
  broker/applications/admin/src/index.js
  broker/applications/extensions/src/api-controllers/index.js
  broker/applications/extensions/src/api-controllers/routes/index.js
  broker/applications/osb-broker/src/api-controllers/routes/index.js
  broker/applications/osb-broker/src/server.js
  broker/config/eventlog-config-admin_app.yml
  broker/config/settings.yml
  broker/data-access-layer/broker-client/src/ServiceBrokerClient.js
  broker/data-access-layer/db/DBManager/DBManager.js
  broker/package.json
  broker/test/test_broker/acceptance/service-fabrik-admin.backups.director.spec.js
  broker/test/test_broker/acceptance/service-fabrik-admin.deployments.backups.director.spec.js
  broker/test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
  broker/test/test_broker/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  broker/test/test_broker/acceptance/service-fabrik-admin.updates.spec.js
  broker/test/test_broker/mocks/serviceBrokerClient.js
  broker/test/test_broker/support/apps.js
  helm-charts/interoperator/conf/settings.yaml
Labels: PipeLine:yet-to-run

#848 Node modulerizing Docker folder
  broker/applications/extensions/package.json
  broker/applications/extensions/src/api-controllers/ServiceFabrikApiController.js
  broker/applications/operators/StartDockerOperators.js
  broker/applications/operators/docker-operator/DockerImageLoaderService.js
  broker/applications/operators/docker-operator/DockerService.js
  broker/data-access-layer/docker/.eslintignore
  broker/data-access-layer/docker/.eslintrc.json
  broker/data-access-layer/docker/.prettierrc
  broker/data-access-layer/docker/package.json
  broker/data-access-layer/docker/src/Docker.js
  broker/data-access-layer/docker/src/DockerClient.js
  broker/data-access-layer/docker/src/DockerCredentials.js
  broker/data-access-layer/docker/src/DockerPortRegistry.js
  broker/data-access-layer/docker/src/index.js
  broker/package.json
  broker/test/test_broker/acceptance/dashboard.docker.spec.js
  broker/test/test_broker/acceptance/service-broker-api.instances.docker.spec.js
  broker/test/test_broker/docker.DockerCredentials.spec.js
  broker/test/test_broker/docker.DockerPortRegistry.spec.js
  broker/test/test_broker/operators.DockerService.spec.js
Labels: unscheduled

#847 Adding default login_hint as sap.ids
  broker/applications/extensions/src/api-controllers/DashboardController.js
  broker/test/test_broker/acceptance/dashboard.director.spec.js
  broker/test/test_broker/acceptance/dashboard.docker.spec.js
  broker/test/test_broker/acceptance/dashboard.virtualHost.spec.js
  broker/test/test_broker/mocks/uaa.js
Labels: DO NOT MERGE, unscheduled

#850 Pass selfsigned module to generate ssl certificate
  broker/applications/operators/bosh-operator/DirectorService.js
  broker/applications/package.json
Labels: unscheduled

#844 Introducing Resource Aware scheduler
  README.md
  docs/Interoperator.md
  docs/images/GardenerWorkers1.png
  docs/images/GardenerWorkers2.png
  docs/interoperator-scheduler.md
  helm-charts/interoperator/crds/sfcluster.yaml
  interoperator/Makefile
  interoperator/PROJECT
  interoperator/api/resource/v1alpha1/groupversion_info.go
  interoperator/api/resource/v1alpha1/resource_list.go
  interoperator/api/resource/v1alpha1/resource_list_test.go
  interoperator/api/resource/v1alpha1/sfcluster_types.go
  interoperator/api/resource/v1alpha1/zz_generated.deepcopy.go
  interoperator/config/crd/bases/resource.servicefabrik.io_sfclusters.yaml
  interoperator/controllers/multiclusterdeploy/setup_multiclusterdeploy.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/sfclusterreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/sfclusterreplicator_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/suite_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/clusterwatcher.go
  interoperator/controllers/multiclusterdeploy/watchmanager/clusterwatcher_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/internal.go
  interoperator/controllers/multiclusterdeploy/watchmanager/internal_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/manager.go
  interoperator/controllers/multiclusterdeploy/watchmanager/watchmanager_suite_test.go
  interoperator/controllers/provisioners/setup_provisioners.go
  interoperator/controllers/provisioners/sfclusterusage/sfclusterusage_controller.go
  interoperator/controllers/provisioners/sfclusterusage/sfclusterusage_controller_test.go
  interoperator/controllers/provisioners/sfclusterusage/suite_test.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller_test.go
  interoperator/pkg/client/clientset/versioned/clientset.go
  interoperator/pkg/client/clientset/versioned/fake/clientset_generated.go
  interoperator/pkg/client/clientset/versioned/fake/register.go
  interoperator/pkg/client/clientset/versioned/scheme/register.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/doc.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/fake/doc.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/fake/fake_resource_client.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/fake/fake_sfcluster.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/generated_expansion.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/resource_client.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/sfcluster.go
  interoperator/pkg/constants/constants.go
  interoperator/pkg/watches/watches.go
Labels: unscheduled

#854 [interoperator] Make Metric endpoints public
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  interoperator/Makefile
  interoperator/config/certmanager/certificate.yaml
  interoperator/config/certmanager/kustomizeconfig.yaml
  interoperator/config/default/kustomization.yaml
  interoperator/config/default/manager_auth_proxy_patch.yaml
  interoperator/config/default/manager_prometheus_metrics_patch.yaml
  interoperator/config/default/webhookcainjection_patch.yaml
  interoperator/config/prometheus/kustomization.yaml
  interoperator/config/prometheus/monitor.yaml
  interoperator/config/rbac/auth_proxy_client_clusterrole.yaml
  interoperator/config/rbac/auth_proxy_service.yaml
  interoperator/config/rbac/kustomization.yaml
  interoperator/go.mod
  interoperator/go.sum
  interoperator/internal/config/config.go
  interoperator/internal/dynamic/dynamic.go
  interoperator/internal/properties/properties.go
  interoperator/pkg/utils/owner_reference.go
  interoperator/pkg/utils/owner_reference_test.go
Labels: unscheduled

#855 Updating broker/Interoperator docker image versions
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#856 Adding Helm Chart Package: 0.8.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.8.0.tgz
Labels: unscheduled

#857 ArchiveMeteredEvents Job should delete excluded sfevents also
  broker/core/scheduler-jobs/src/jobs/ArchiveMeteredEventsJob.js
  broker/test/test_broker/jobs.ArchiveMeteredEventsJob.spec.js
Labels: unscheduled
