Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-10, with the labels that each got.

#1083 [Bug] Fix state getting lost on parallel requests
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller_test.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller_test.go
Labels: PipeLine:Green, go

#1091 Updating broker/Interoperator docker image versions:0.11.1
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1092 Adding Helm Chart Package: 0.11.1
  helm-charts/index.yaml
  helm-charts/interoperator-0.11.1.tgz
Labels: unscheduled

#1090 Update nock to 13.0.4
  broker/package.json
  broker/test/test_broker/acceptance/service-broker-api.catalog.spec.js
  broker/test/test_broker/eventmesh.LockManager.spec.js
  broker/test/test_broker/mocks/agent.js
  broker/test/test_broker/mocks/apiServerEventMesh.js
  broker/test/test_broker/mocks/cloudController.js
  broker/test/test_broker/mocks/serviceBrokerClient.js
  broker/test/test_broker/mocks/uaa.js
  broker/test/test_broker/operators.DirectorService.spec.js
  broker/test/test_broker/utils.spec.js
Labels: unscheduled

#1098 Support uppercase instance id
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/core/utils/src/commonFunctions.js
  broker/test/test_broker/fabrik.ServiceBrokerApi.spec.js
  broker/test/test_broker/utils.spec.js
  docs/Interoperator.md
  helm-charts/interoperator/crds/sfserviceinstance.yaml
  interoperator/api/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfserviceinstances.yaml
  operator-apis/internal/handlers/handlers.go
  operator-apis/internal/handlers/utils.go
  operator-apis/internal/handlers/utils_test.go
Labels: PipeLine:Green

#1104 Updating broker/Interoperator docker image versions:0.11.2
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1105 Adding Helm Chart Package: 0.11.2
  helm-charts/index.yaml
  helm-charts/interoperator-0.11.2.tgz
Labels: unscheduled

#1089 osb-broker UTs restructured
  broker/applications/admin/test/acceptance/service-fabrik-admin.backups.director.spec.js
  broker/applications/admin/test/acceptance/service-fabrik-admin.deployments.backups.director.spec.js
  broker/applications/admin/test/acceptance/service-fabrik-admin.instances.director.spec.js
  broker/applications/admin/test/acceptance/service-fabrik-admin.internal-db.lifecycle.spec.js
  broker/applications/admin/test/acceptance/service-fabrik-admin.updates.spec.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.catalog.spec.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.instances.director.spec.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.instances.docker.spec.js
  broker/applications/osb-broker/test/broker.middleware.QuotaClient.spec.js
  broker/applications/osb-broker/test/broker.middleware.spec.js
  broker/test/init
  broker/test/test_broker/acceptance/dashboard.director.spec.js
  broker/test/test_broker/mocks/index.js
Labels: unscheduled

#1108 increase upper bound on file fetched from iaas store
  broker/data-access-layer/iaas/src/BackupStore.js
Labels: unscheduled

#1084 Interop/dep update
  interoperator/controllers/multiclusterdeploy/watchmanager/clusterwatcher.go
  interoperator/controllers/schedulers/setup_schedulers.go
  interoperator/controllers/schedulers/sfserviceinstanceupdater/sfserviceinstanceupdater_controller_test.go
  interoperator/go.mod
  interoperator/go.sum
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfplan.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfservice.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfservicebinding.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/fake/fake_sfserviceinstance.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfplan.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfservice.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfservicebinding.go
  interoperator/pkg/client/clientset/versioned/typed/osb/v1alpha1/sfserviceinstance.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/fake/fake_sfcluster.go
  interoperator/pkg/client/clientset/versioned/typed/resource/v1alpha1/sfcluster.go
  operator-apis/Dockerfile
  operator-apis/go.mod
  operator-apis/go.sum
  operator-apis/internal/handlers/handlers.go
  operator-apis/internal/handlers/handlers_test.go
Labels: PipeLine:Green, dependencies, go

#1106 restructured UTs of quota-app, reports and scheduler
  broker/applications/quota-app/test/controllers.QuotaApiController.spec.js
  broker/applications/reports/test/acceptance/service-fabrik-report.backupreport.spec.js
  broker/applications/reports/test/reports.BackupReportManager.spec.js
  broker/applications/scheduler/test/JobScheduler.spec.js
  broker/applications/scheduler/test/maintenance.MaintenanceManager.spec.js
Labels: unscheduled

#1110 Restructured UTs of extension application
  broker/applications/extensions/test/acceptance/dashboard.director.spec.js
  broker/applications/extensions/test/acceptance/dashboard.docker.spec.js
  broker/applications/extensions/test/acceptance/dashboard.virtualHost.spec.js
  broker/applications/extensions/test/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  broker/applications/extensions/test/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  broker/applications/extensions/test/acceptance/service-fabrik-api.info.spec.js
  broker/applications/extensions/test/acceptance/service-fabrik-api.instances.director.spec.js
  broker/test/test_broker/jobs.BackupReaperJobs.spec.js
Labels: unscheduled

#1097 adding middleware for injecting plan in the request
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/applications/osb-broker/src/api-controllers/routes/broker/v2.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  broker/core/utils/src/commonFunctions.js
  broker/test/test_broker/fabrik.ServiceBrokerApi.spec.js
Labels: PipeLine:Green

#1121 Update Service Fabrik Golang Libraries
  interoperator/go.mod
  interoperator/go.sum
  operator-apis/go.mod
  operator-apis/go.sum
Labels: PipeLine:Green, unscheduled

#1120 Restructured UTs of operators
  broker/applications/operators/test/operators.BOSHManager.spec.js
  broker/applications/operators/test/operators.BackupService.spec.js
  broker/applications/operators/test/operators.BackupStatusPoller.js
  broker/applications/operators/test/operators.BaseStatusPoller.spec.js
  broker/applications/operators/test/operators.BoshPostProcessingPoller.spec.js
  broker/applications/operators/test/operators.BoshRestoreService.spec.js
  broker/applications/operators/test/operators.BoshRestoreStatusPoller.spec.js
  broker/applications/operators/test/operators.BoshstaggeredDeploymentPoller.spec.js
  broker/applications/operators/test/operators.DefaultBackupManager.spec.js
  broker/applications/operators/test/operators.DefaultBoshRestoreOperator.spec.js
  broker/applications/operators/test/operators.DefaultRestoreOperator.spec.js
  broker/applications/operators/test/operators.DockerManager.spec.js
  broker/applications/operators/test/operators.DockerService.spec.js
  broker/applications/operators/test/operators.MultitenancyOperator.spec.js
  broker/applications/operators/test/operators.MultitenancyService.spec.js
  broker/applications/operators/test/operators.RestoreService.spec.js
  broker/applications/operators/test/operators.VirtualHostManager.spec.js
  broker/applications/operators/test/operators.VirtualHostService.spec.js
  broker/applications/operators/test/operators.serviceflow.SerialServiceFlow.spec.js
  broker/applications/operators/test/operators.serviceflow.tasks.BlueprintTask.spec.js
  broker/applications/operators/test/operators.serviceflow.tasks.ServiceInstanceBackupTask.spec.js
  broker/applications/operators/test/operators.serviceflow.tasks.ServiceInstanceUpdateTask.spec.js
  broker/applications/operators/test/operators.serviceflow.tasks.Task.spec.js
  broker/applications/operators/test/operators.serviceflow.tasks.TaskFabrik.spec.js
  broker/applications/operators/test/operators.serviceflow.tasks.TaskOperator.spec.js
Labels: unscheduled

#1123 Restructured UTs of Utils,SchedularJobs and Osb-broker
  broker/applications/osb-broker/test/fabrik.ServiceBrokerApi.spec.js
  broker/core/scheduler-jobs/test/jobs.ArchiveMeteredEventsJob.spec.js
  broker/core/scheduler-jobs/test/jobs.BackupReaperJobs.spec.js
  broker/core/scheduler-jobs/test/jobs.BaseJob.spec.js
  broker/core/scheduler-jobs/test/jobs.DbCollectionReaperJob.spec.js
  broker/core/scheduler-jobs/test/jobs.JobFabrik.spec.js
  broker/core/scheduler-jobs/test/jobs.MeteringInstanceJobs.spec.js
  broker/core/scheduler-jobs/test/jobs.OperationStatusPollerJob.spec.js
  broker/core/scheduler-jobs/test/jobs.ScheduleBackupJob.spec.js
  broker/core/scheduler-jobs/test/jobs.ScheduleManager.spec.js
  broker/core/scheduler-jobs/test/jobs.ScheduledOobDeploymentBackupJob.spec.js
  broker/core/scheduler-jobs/test/jobs.Scheduler.spec.js
  broker/core/scheduler-jobs/test/jobs.ServiceInstanceUpdateJob.spec.js
  broker/core/utils/test/db.Repository.spec.js
  broker/core/utils/test/errors.spec.js
  broker/core/utils/test/uitls.RetryOperation.spec.js
  broker/core/utils/test/utils.DeploymentHookClient.spec.js
  broker/core/utils/test/utils.EncryptionManager.spec.js
  broker/core/utils/test/utils.EventLogDBClient.spec.js
  broker/core/utils/test/utils.EventLogDomainSocketClient.spec.js
  broker/core/utils/test/utils.EventLogRiemannClient.spec.js
  broker/core/utils/test/utils.HttpClient.spec.js
  broker/core/utils/test/utils.RsaKeyGenerator.spec.js
  broker/core/utils/test/utils.ServiceBrokerClient.spec.js
  broker/core/utils/test/utils.ServiceflowMapper.js
  broker/core/utils/test/utils.spec.js
  broker/test/init
Labels: unscheduled
