Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-11, with the labels that each got.

#1124 Restructured UTs of express-commons, models, PM and PS
  broker/core/express-commons/test/common.middleware.spec.js
  broker/core/models/test/models.Plan.spec.js
  broker/core/models/test/models.Service.spec.js
  broker/core/models/test/models.catalog.spec.js
  broker/core/platform-managers/test/fabrik.CfPlatformManager.spec.js
  broker/core/provisioner-services/test/operators.BaseDirectorService.spec.js
  broker/core/provisioner-services/test/operators.DirectorService.ratelimits.spec.js
  broker/core/provisioner-services/test/operators.DirectorService.spec.js
Labels: unscheduled

#1127 Restructured UTs of bosh and cf
  broker/data-access-layer/bosh/test/bosh.BoshDirectorClient.spec.js
  broker/data-access-layer/bosh/test/bosh.BoshSshClient.spec.js
  broker/data-access-layer/bosh/test/bosh.EvaluationContext.spec.js
  broker/data-access-layer/bosh/test/bosh.NetworkSegmentIndex.spec.js
  broker/data-access-layer/bosh/test/bosh.manifest.AddOns.spec.js
  broker/data-access-layer/bosh/test/bosh.manifest.Header.spec.js
  broker/data-access-layer/bosh/test/bosh.manifest.Network.spec.js
  broker/data-access-layer/bosh/test/bosh.manifest.Networks.spec.js
  broker/data-access-layer/cf/test/cf.CloudControllerClient.spec.js
  broker/data-access-layer/cf/test/cf.ServiceFabrikClient.spec.js
  broker/data-access-layer/cf/test/cf.TokenInfo.spec.js
  broker/data-access-layer/cf/test/cf.TokenIssuer.spec.js
  broker/data-access-layer/cf/test/cf.UaaClient.spec.js
  broker/test/init
Labels: unscheduled

#1126 Interoperator Improvements suggested by CFforK8S
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/watchmanager/internal.go
  interoperator/internal/dynamic/dynamic.go
  interoperator/internal/renderer/factory/factory.go
  interoperator/internal/renderer/gotemplate/renderer.go
  interoperator/pkg/cluster/registry/registry.go
  interoperator/pkg/errors/errors.go
Labels: unscheduled

#1122 Update kubernetes client to latest
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
Labels: dependencies, javascript

#1107 Adding stricter Sub account check for quota check
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
Labels: unscheduled

#1082 Switching dependency from Riemannjs to Riemann
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/core/utils/test/utils.EventLogRiemannClient.spec.js
  broker/data-access-layer/event-logger/src/EventLogRiemannClient.js
Labels: PipeLine:Green, unscheduled

#1132 Restructured UTs of rest modules of data-access-layer
  broker/data-access-layer/db/test/db.DbConnectionManager.spec.js
  broker/data-access-layer/db/test/fabrik.DBManager.spec.js
  broker/data-access-layer/docker/test/docker.DockerCredentials.spec.js
  broker/data-access-layer/docker/test/docker.DockerPortRegistry.spec.js
  broker/data-access-layer/event-logger/test/EventLogInterceptor.spec.js
  broker/data-access-layer/eventmesh/test/common.UnlockResourcePoller.spec.js
  broker/data-access-layer/eventmesh/test/eventmesh.ApiServerClient.spec.js
  broker/data-access-layer/eventmesh/test/eventmesh.LockManager.spec.js
  broker/data-access-layer/eventmesh/test/watcher.ApiServerClientWatcher.spec.js
  broker/data-access-layer/metering/test/metering.MeteringClient.spec.js
  broker/data-access-layer/oob-manager/test/fabrik.OOBBackupManager.spec.js
  broker/data-access-layer/service-agent/test/fabrik.Agent.spec.js
Labels: unscheduled

#1135 reverting upgrade to riemann nodejs client 2.0.0
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/core/utils/test/utils.EventLogRiemannClient.spec.js
  broker/data-access-layer/event-logger/src/EventLogRiemannClient.js
Labels: unscheduled

#1134 Restructured UTs of deployment-hooks
  broker/applications/deployment_hooks/test/deployment-hooks-api.spec.js
  broker/applications/deployment_hooks/test/deployment-hooks.actions.ActionManager.spec.js
  broker/applications/deployment_hooks/test/deployment-hooks.actions.BaseAction.spec.js
  broker/applications/deployment_hooks/test/deployment-hooks.actions.JSExecutor.spec.js
  broker/applications/deployment_hooks/test/deployment-hooks.utils.ScriptExecutor.spec.js
  broker/applications/deployment_hooks/test/mocha_deployment_hooks.opts
  broker/applications/deployment_hooks/test/mocks/index.js
  broker/applications/deployment_hooks/test/support/Recorder.js
  broker/applications/deployment_hooks/test/support/apps.js
  broker/applications/deployment_hooks/test/support/index.js
  broker/data-access-layer/broker-client/test/utils.ServiceBrokerClient.spec.js
  broker/data-access-layer/event-logger/test/utils.EventLogDBClient.spec.js
  broker/data-access-layer/event-logger/test/utils.EventLogDomainSocketClient.spec.js
  broker/data-access-layer/event-logger/test/utils.EventLogRiemannClient.spec.js
  broker/test/init
  broker/test/test_deployment_hooks/mocha_deployment_hooks.opts
Labels: unscheduled

#1143 Revert "Adding stricter Sub account check for quota check"
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
Labels: unscheduled

#1151 Revert "Adding stricter Sub account check for quota check (#1107)" (#…
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
Labels: unscheduled

#1142 Update AJV from 5.0.0 to 6.12.6
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/package.json
  broker/tools/module-generator/files/package.json
Labels: PipeLine:Green

#1140 Merged broker and deployment-hooks in init script
  broker/package.json
  broker/test/init
Labels: unscheduled

#1144 Fix docker instance update
  broker/applications/operators/src/docker-operator/DockerOperator.js
  broker/applications/operators/src/docker-operator/DockerService.js
  broker/applications/operators/test/operators.DockerService.spec.js
Labels: unscheduled

#1153 Switching to riemann 2 from riemannjs
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/data-access-layer/event-logger/src/EventLogRiemannClient.js
  broker/data-access-layer/event-logger/test/utils.EventLogRiemannClient.spec.js
Labels: unscheduled

#1139 Updating bluebird from 3.4.0 to 3.7.2
  .github/dependabot.yml
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/data-access-layer/bosh/test/bosh.BoshDirectorClient.spec.js
Labels: PipeLine:Green, unscheduled
