Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-08, with the labels that each got.

#913 Update CRDs ApiVersion to v1
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/config/crds/backup.servicefabrik.io_v1alpha1_defaultbackups.yaml
  broker/config/crds/backup.servicefabrik.io_v1alpha1_defaultboshrestores.yaml
  broker/config/crds/backup.servicefabrik.io_v1alpha1_defaultrestores.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_directorbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_dockerbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_postgresqlmtbinds.yaml
  broker/config/crds/bind.servicefabrik.io_v1alpha1_virtualhostbinds.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_directors.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_dockers.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_postgresqlmts.yaml
  broker/config/crds/deployment.servicefabrik.io_v1alpha1_virtualhosts.yaml
  broker/config/crds/instance.servicefabrik.io_v1alpha1_sfevents.yaml
  broker/config/crds/lock.servicefabrik.io_v1alpha1_deploymentlocks.yaml
  broker/config/crds/serviceflow.servicefabrik.io_v1alpha1_serialserviceflows.yaml
  broker/config/crds/serviceflow.servicefabrik.io_v1alpha1_tasks.yaml
  broker/config/kubeconfig
  broker/config/settings.yml
  broker/core/utils/src/commonVariables.js
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
  broker/test/test_broker/eventmesh.ApiServerClient.spec.js
  broker/test/test_broker/mocks/apiServerEventMesh.js
  broker/test/test_broker/operators.BOSHManager.spec.js
  broker/test/test_broker/operators.DefaultBackupManager.spec.js
  broker/test/test_broker/operators.DockerManager.spec.js
  broker/test/test_broker/operators.MultitenancyOperator.spec.js
  broker/test/test_broker/operators.VirtualHostManager.spec.js
  broker/test/test_broker/utils.spec.js
  helm-charts/interoperator/crds/sfcluster.yaml
  helm-charts/interoperator/crds/sfplan.yaml
  helm-charts/interoperator/crds/sfservice.yaml
  helm-charts/interoperator/crds/sfservicebinding.yaml
  helm-charts/interoperator/crds/sfserviceinstance.yaml
  interoperator/Makefile
  interoperator/api/osb/v1alpha1/sfplan_types.go
  interoperator/api/osb/v1alpha1/sfservice_types.go
  interoperator/api/osb/v1alpha1/sfservicebinding_types.go
  interoperator/api/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/api/osb/v1alpha1/sfserviceinstance_types_test.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfplans.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfservicebindings.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfserviceinstances.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfservices.yaml
  interoperator/config/crd/bases/resource.servicefabrik.io_sfclusters.yaml
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/scripts/install.sh
Labels: PipeLine:Green, enhancement

#979 Update dependabot.yml
  .github/dependabot.yml
Labels: unscheduled

#904 upgrading winston and winston-syslog to current major versions
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/operators/src/BaseOperator.js
  broker/applications/operators/src/StartDockerOperators.js
  broker/applications/operators/src/backup-operator/BackupService.js
  broker/applications/operators/src/docker-operator/DockerService.js
  broker/applications/operators/src/serviceflow-operator/SerialServiceFlowOperator.js
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/applications/scheduler/src/JobScheduler.js
  broker/core/logging/src/index.js
  broker/core/provisioner-services/src/DirectorService.js
  broker/core/scheduler-jobs/src/Scheduler.js
  broker/core/scheduler-jobs/src/jobs/BackupReaperJob.js
  broker/data-access-layer/bosh/src/BoshDirectorClient.js
  broker/data-access-layer/cf/src/TokenIssuer.js
  broker/data-access-layer/db/src/DBManager.js
  broker/data-access-layer/docker/src/DockerClient.js
  broker/data-access-layer/eventmesh/src/LockManager.js
  broker/data-access-layer/iaas/src/AzureClient.js
  broker/data-access-layer/iaas/src/CloudProviderClient.js
  broker/data-access-layer/iaas/src/GcpClient.js
  broker/data-access-layer/quota/src/TokenIssuer.js
Labels: DO NOT MERGE, PipeLine:yet-to-run, unscheduled

#866 Adding Staticcheck for Interoperator codebase
  .travis.yml
  interoperator/api/osb/v1alpha1/sfservicebinding_types.go
  interoperator/api/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_suite_test.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/suite_test.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller_suite_test.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller_suite_test.go
  interoperator/controllers/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller.go
  interoperator/controllers/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller_suite_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/internal.go
  interoperator/controllers/multiclusterdeploy/watchmanager/manager.go
  interoperator/controllers/provisioners/sfclusterusage/suite_test.go
  interoperator/controllers/provisioners/sfplan/sfplan_controller_suite_test.go
  interoperator/controllers/provisioners/sfservice/sfservice_controller_suite_test.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller_suite_test.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/controllers/provisioners/sfservicebindingcleaner/sfservicebindingcleaner_controller.go
  interoperator/controllers/provisioners/sfservicebindingcleaner/sfservicebindingcleaner_controller_suite_test.go
  interoperator/controllers/provisioners/sfservicebindingcleaner/sfservicebindingcleaner_controller_test.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller_suite_test.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/controllers/schedulers/sfdefaultscheduler/sfdefaultscheduler_controller_suite_test.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller_suit_test.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller_test.go
  interoperator/controllers/schedulers/sfserviceinstancecounter/sfserviceinstancecounter_controller_suit_test.go
  interoperator/controllers/schedulers/sfserviceinstancecounter/sfserviceinstancecounter_controller_test.go
  interoperator/controllers/schedulers/sfserviceinstanceupdater/sfserviceinstanceupdater_controller.go
  interoperator/controllers/schedulers/sfserviceinstanceupdater/sfserviceinstanceupdater_controller_suit_test.go
  interoperator/controllers/schedulers/sfserviceinstanceupdater/sfserviceinstanceupdater_controller_test.go
  interoperator/internal/config/config.go
  interoperator/internal/config/config_test.go
  interoperator/internal/dynamic/dynamic.go
  interoperator/internal/properties/properties.go
  interoperator/internal/provisioner/provisioner.go
  interoperator/internal/renderer/gotemplate/output.go
  interoperator/internal/resources/resources.go
  interoperator/internal/resources/resources_test.go
  interoperator/internal/services/services_test.go
  interoperator/pkg/client/clientset/versioned/clientset.go
  interoperator/pkg/cluster/registry/registry.go
  interoperator/pkg/utils/owner_reference.go
  interoperator/pkg/utils/owner_reference_test.go
  interoperator/pkg/watches/watches.go
  interoperator/pkg/watches/watches_test.go
Labels: PipeLine:Green, unscheduled

#988 Replicate imagePull secrets in mcd
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
Labels: unscheduled

#990 [piper] Automate Interoperator release creation
  Jenkinsfile
Labels: unscheduled

#991 Updating broker/Interoperator docker image versions:0.9.1
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#992 Adding Helm Chart Package: 0.9.1
  helm-charts/index.yaml
  helm-charts/interoperator-0.9.1.tgz
Labels: unscheduled

#993 Update Jenkinsfile
  Jenkinsfile
Labels: unscheduled

#983 Export Custom Metrics
  docs/Interoperator-metrics.md
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/sfclusterreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/sfclusterreplicator_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/go.mod
  interoperator/go.sum
Labels: unscheduled

#1000 Removing scheduler type config and default scheduler for pure Interoperator based deployment
  helm-charts/interoperator/templates/interoperator_config.yaml
  helm-charts/interoperator/values.yaml
  interoperator/controllers/schedulers/setup_schedulers.go
  interoperator/controllers/schedulers/sfdefaultscheduler/sfdefaultscheduler_controller.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller.go
  interoperator/internal/config/config.go
  interoperator/internal/config/config_test.go
  interoperator/pkg/constants/constants.go
Labels: unscheduled

#982 Removing org based quota check.
  broker/applications/osb-broker/src/api-controllers/middleware/QuotaClient.js
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/applications/quota-app/src/QuotaApiController.js
  broker/data-access-layer/quota/src/BaseQuotaManager.js
  broker/data-access-layer/quota/src/QuotaAPIClient.js
  broker/data-access-layer/quota/src/k8s-platform-quota-manager/K8SPlatformQuotaManager.js
  broker/test/test_broker/broker.middleware.QuotaClient.spec.js
  broker/test/test_broker/broker.middleware.spec.js
  broker/test/test_broker/controllers.QuotaApiController.spec.js
  broker/test/test_broker/quota.QuotaAPIClient.spec.js
  broker/test/test_broker/quota.QuotaManager.spec.js
Labels: unscheduled

#1001 Fix delete failure before create over
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller_test.go
Labels: unscheduled

#1003 Updating broker/Interoperator docker image versions:0.9.2
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1004 Adding Helm Chart Package: 0.9.2
  helm-charts/index.yaml
  helm-charts/interoperator-0.9.2.tgz
Labels: unscheduled

#1002 Prefix the release tag with v
  Jenkinsfile
Labels: unscheduled

#1010 Interoperator Multicluster Flow Diagrams
  docs/Interoperator-multiclutser-flow.md
  docs/images/mcd_instancereplicator.png
  docs/images/mcd_provisioner.png
  docs/images/multiclusterflow.png
  docs/mcd_instancereplicator.wsd
  docs/mcd_provisioner.wsd
  docs/multiclusterflow.wsd
Labels: unscheduled

#1012 Fix intermitent travis fail for golang
  interoperator/controllers/schedulers/sfserviceinstancecounter/sfserviceinstancecounter_controller_test.go
Labels: unscheduled

#1013 Fix crd ver upgrade
  helm-charts/interoperator/conf/settings.yaml
  interoperator/controllers/multiclusterdeploy/setup_multiclusterdeploy.go
  interoperator/controllers/multiclusterdeploy/upgrade_hook.go
Labels: unscheduled

#1014 Updating broker/Interoperator docker image versions:0.10.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1015 Adding Helm Chart Package: 0.10.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.10.0.tgz
Labels: unscheduled
