Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-07, with the labels that each got.

#875 Use alphine as Base Image for Interoperator (#860)
  interoperator/Dockerfile
Labels: unscheduled

#859 Removing unneeded Node modules and Stripping down Dockerfile for broker
  broker/Dockerfile
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
Labels: PipeLine:Green, unscheduled

#877 Change Docker build context
  .dockerignore
  broker/Dockerfile
  interoperator/.dockerignore
  interoperator/Dockerfile
Labels: DO NOT MERGE, unscheduled

#878 Moving DirectorService in the separate module
  broker/applications/admin/src/api-controllers/ServiceFabrikAdminController.js
  broker/applications/deployment_hooks/.eslintignore
  broker/applications/deployment_hooks/.eslintrc.json
  broker/applications/deployment_hooks/.prettierrc
  broker/applications/deployment_hooks/src/HookServer.js
  broker/applications/deployment_hooks/src/lib/LoadDeploymentActions.js
  broker/applications/deployment_hooks/src/lib/actions/JSExecutor.js
  broker/applications/extensions/src/api-controllers/DashboardController.js
  broker/applications/extensions/src/api-controllers/ServiceFabrikApiController.js
  broker/applications/operators/.eslintignore
  broker/applications/operators/.eslintrc.json
  broker/applications/operators/.prettierrc
  broker/applications/operators/src/backup-operator/BackupService.js
  broker/applications/operators/src/bosh-operator/BoshBindOperator.js
  broker/applications/operators/src/bosh-operator/BoshOperator.js
  broker/applications/operators/src/bosh-operator/BoshPostProcessingPoller.js
  broker/applications/operators/src/bosh-operator/BoshStaggeredDeploymentPoller.js
  broker/applications/operators/src/bosh-operator/BoshTaskStatusPoller.js
  broker/applications/operators/src/bosh-operator/index.js
  broker/applications/operators/src/bosh-restore-operator/BoshRestoreService.js
  broker/applications/operators/src/docker-operator/DockerService.js
  broker/applications/operators/src/multitenancy-operator/MultitenancyBindService.js
  broker/applications/operators/src/multitenancy-operator/MultitenancyService.js
  broker/applications/operators/src/restore-operator/RestoreService.js
  broker/applications/operators/src/virtualhost-operator/VirtualHostService.js
  broker/applications/reports/.eslintignore
  broker/applications/reports/.eslintrc.json
  broker/applications/reports/.prettierrc
  broker/applications/reports/src/index.js
  broker/applications/scheduler/.eslintignore
  broker/applications/scheduler/.eslintrc.json
  broker/applications/scheduler/.prettierrc
  broker/core/provisioner-services/.eslintignore
  broker/core/provisioner-services/.eslintrc.json
  broker/core/provisioner-services/.prettierrc
  broker/core/provisioner-services/package.json
  broker/core/provisioner-services/src/BaseDirectorService.js
  broker/core/provisioner-services/src/BaseService.js
  broker/core/provisioner-services/src/DirectorService.js
  broker/core/provisioner-services/src/index.js
  broker/core/scheduler-jobs/src/jobs/ServiceInstanceUpdateJob.js
  broker/data-access-layer/db/src/DBManager.js
  broker/package.json
  broker/test/test_broker/EventLogInterceptor.spec.js
  broker/test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
  broker/test/test_broker/bosh.NetworkSegmentIndex.spec.js
  broker/test/test_broker/fabrik.DBManager.spec.js
  broker/test/test_broker/mocks/cloudController.js
  broker/test/test_broker/operators.BOSHManager.spec.js
  broker/test/test_broker/operators.BaseDirectorService.spec.js
  broker/test/test_broker/operators.BoshPostProcessingPoller.spec.js
  broker/test/test_broker/operators.BoshstaggeredDeploymentPoller.spec.js
  broker/test/test_broker/operators.DirectorService.ratelimits.spec.js
  broker/test/test_broker/operators.DirectorService.spec.js
  broker/test/test_broker/utils.spec.js
Labels: PipeLine:Green, unscheduled

#876 Triggering deletion of the BOSH deployment in case of create failed s…
  broker/core/provisioner-services/src/DirectorService.js
  broker/test/test_broker/operators.DirectorService.spec.js
Labels: PipeLine:Green, unscheduled

#880 moving deploymentHooksClient to common-utils
  broker/core/provisioner-services/src/DirectorService.js
  broker/core/utils/src/DeploymentHookClient.js
  broker/core/utils/src/index.js
  broker/test/test_broker/utils.DeploymentHookClient.spec.js
Labels: unscheduled

#879 minor version upgrades of external dependencies except bluebird
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
Labels: unscheduled

#901 Add Full example for SFPlan in docs
  docs/Interoperator.md
Labels: unscheduled

#902 Updating broker/Interoperator docker image versions
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#903 Adding Helm Chart Package: 0.9.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.9.0.tgz
Labels: unscheduled

#905 adjusting ajv, rxjs, lodash versions
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
Labels: unscheduled

#900 upgrading google compute, storage and azure compute libs
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/data-access-layer/iaas/src/GcpClient.js
  broker/test/test_broker/iaas.AzureClient.spec.js
  broker/test/test_broker/iaas.GcpClient.spec.js
Labels: unscheduled

#921 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: unscheduled

#922 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: unscheduled

#919 major version upgrades of mongoose and uuid
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/test/test_broker/iaas.AzureClient.spec.js
Labels: unscheduled

#920 including failed and in_progress resources as well in deployment summary API
  broker/applications/admin/src/api-controllers/ServiceFabrikAdminController.js
  broker/data-access-layer/iaas/src/GcpClient.js
  broker/test/test_broker/acceptance/service-fabrik-admin.instances.director.spec.js
Labels: unscheduled

#923 adding dependabot.yml
  .github/dependabot.yml
Labels: unscheduled

#968 keeping only admin and osb-broker in dependabot config
  .github/dependabot.yml
Labels: unscheduled

#975 Update dependabot.yml
  .github/dependabot.yml
Labels: unscheduled

#974 [Piper] initial setup for interoperator
  Jenkinsfile
  broker/applications/osb-broker/wss-unified-agent.config
  interoperator/wss-unified-agent.config
Labels: unscheduled
