Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-09, with the labels that each got.

#1019 Fetch Provisioner always before replicating
  interoperator/internal/provisioner/provisioner.go
  interoperator/internal/provisioner/provisioner_test.go
Labels: unscheduled

#1020 Update to golang version 1.15
  .travis.yml
  interoperator/Dockerfile
  interoperator/go.mod
Labels: unscheduled

#1021 Update node version to 12.18 from 12.14
  .travis.yml
  broker/Dockerfile
Labels: unscheduled

#1011 [Bug] Fix NS replication when NS sepration is disabled
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller_test.go
Labels: unscheduled

#989 Introducing operator-apis application
  .travis.yml
  Jenkinsfile
  helm-charts/interoperator/templates/operator_api_app.yaml
  helm-charts/interoperator/values.yaml
  operator-apis/.gitignore
  operator-apis/Dockerfile
  operator-apis/go.mod
  operator-apis/go.sum
  operator-apis/internal/config/config.go
  operator-apis/internal/config/config_test.go
  operator-apis/internal/constants/constants.go
  operator-apis/internal/handlers/handlers.go
  operator-apis/internal/handlers/handlers_suite_test.go
  operator-apis/internal/handlers/handlers_test.go
  operator-apis/internal/handlers/responses.go
  operator-apis/internal/handlers/utils.go
  operator-apis/internal/middlewares/middlewares.go
  operator-apis/internal/middlewares/middlewares_test.go
  operator-apis/internal/router/router.go
  operator-apis/internal/router/router_test.go
  operator-apis/main.go
  operator-apis/wss-unified-agent.config
Labels: DO NOT MERGE, unscheduled

#1025 fixing Dockerfile for operator-apis
  operator-apis/Dockerfile
Labels: unscheduled

#1026 Adding flag failOnSevereVulnerabilities for protecodescan
  Jenkinsfile
Labels: unscheduled

#1023 upgrading lodash to 4.17.20
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
Labels: unscheduled

#1031 Run `go mod tidy` for operator apis
  operator-apis/go.mod
  operator-apis/go.sum
Labels: unscheduled

#1029 Allow custom error messages for invalid quota & send instance_id
  broker/applications/osb-broker/src/api-controllers/middleware/QuotaClient.js
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/test/test_broker/broker.middleware.QuotaClient.spec.js
  broker/test/test_broker/broker.middleware.spec.js
Labels: unscheduled

#1032 Hotfix 2020.t08b quota
  broker/applications/osb-broker/src/api-controllers/middleware/QuotaClient.js
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/test/test_broker/broker.middleware.QuotaClient.spec.js
  broker/test/test_broker/broker.middleware.spec.js
Labels: unscheduled

#1030 Multi-AZ and High availability for Interoperator
  broker/applications/osb-broker/src/server.js
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/operator_api_app.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/internal/provisioner/mock_provisioner/mock_provisioner.go
  interoperator/internal/provisioner/provisioner.go
  interoperator/internal/provisioner/provisioner_suite_test.go
  interoperator/internal/provisioner/provisioner_test.go
  interoperator/pkg/constants/constants.go
  interoperator/pkg/constants/multiclusterdeploy.go
  interoperator/pkg/watches/watches.go
Labels: High Availability, unscheduled

#1041 Removing Jenkins file and other configs
  Jenkinsfile
  broker/applications/osb-broker/wss-unified-agent.config
  interoperator/wss-unified-agent.config
  operator-apis/wss-unified-agent.config
Labels: unscheduled

#1033 upgrades suggested by dependabot
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
Labels: PipeLine:Green, unscheduled

#1049 Ensure credentials are stored as Secrets
  broker/core/app-config/src/index.js
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/operator_api_app.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/templates/secret.yaml
Labels: PipeLine:Green, unscheduled

#1050 fixing npm test-cov command
  broker/test/test_broker/broker.middleware.spec.js
Labels: unscheduled

#1048 Set log level to debug for pre-actions
  broker/applications/deployment_hooks/src/lib/controllers/DeploymentHookController.js
  broker/core/provisioner-services/src/DirectorService.js
Labels: unscheduled

#1042 Multi-AZ and High availability for Interoperator
  docs/Interoperator.md
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/operator_api_app.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1051 doc for operator apis
  docs/operator_apis.md
Labels: unscheduled

#1059 Updating broker/Interoperator docker image versions:0.11.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1060 Adding Helm Chart Package: 0.11.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.11.0.tgz
Labels: unscheduled

#1061 Enable Dependabot for golang
  .github/dependabot.yml
  .travis.yml
Labels: dependencies, unscheduled

#1058 Update dependabot.yml to include operator-apis
  .github/dependabot.yml
Labels: unscheduled

#1065 Sample Grafana Dashboard
  docs/Interoperator-metrics.md
  docs/grafana.json
Labels: unscheduled

#1066 Update Flow Diagrams
  docs/images/mcd_instancereplicator.png
  docs/images/provisioner_instance.png
  docs/mcd_instancereplicator.wsd
  docs/provisioner_instance.wsd
Labels: unscheduled

#1067 Fix static check errors in Operator API
  operator-apis/internal/handlers/handlers.go
  operator-apis/internal/middlewares/middlewares.go
  operator-apis/internal/router/router.go
Labels: unscheduled

#1068 [rel-branch] changes to support sf-mongo binding rotation
  broker/data-access-layer/db/src/DBManager.js
  broker/test/test_broker/fabrik.DBManager.spec.js
Labels: unscheduled

#1064 changes to support sf-mongo binding rotation
  broker/data-access-layer/db/src/DBManager.js
  broker/test/test_broker/fabrik.DBManager.spec.js
Labels: DO NOT MERGE, unscheduled
