Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2020-04, with the labels that each got.

#803 Refactor Quota Manager
  api-controllers/ServiceBrokerApiController.js
  broker/lib/middleware.js
  common/utils/index.js
  quota/BaseQuotaManager.js
  quota/QuotaAPIClient.js
  quota/QuotaManager.js
  quota/cf-platform-quota-manager/CFPlatformQuotaManager.js
  quota/cf-platform-quota-manager/index.js
  quota/index.js
  quota/k8s-platform-quota-manager/K8SPlatformQuotaManager.js
  quota/k8s-platform-quota-manager/index.js
  test/test_broker/broker.middleware.spec.js
  test/test_broker/quota.CFQuotaManager.spec.js
  test/test_broker/quota.QuotaAPIClient.spec.js
Labels: PipeLine:Green, unscheduled

#804 Removing code to register CRDs
  broker/server.js
  common/constants.js
  common/utils/index.js
  data-access-layer/eventmesh/ApiServerClient.js
  test/test_broker/mocks/apiServerEventMesh.js
  test/test_broker/utils.spec.js
Labels: unscheduled

#809 Adding flag to conditionally disable iptables_manager job in services
  data-access-layer/bosh/manifest/Addons.js
  operators/bosh-operator/DirectorService.js
  test/test_broker/bosh.manifest.AddOns.spec.js
Labels: unscheduled

#808 Moving CRDs to conf folder
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/conf/sfcluster.yaml
  helm-charts/interoperator/conf/sfplan.yaml
  helm-charts/interoperator/conf/sfservice.yaml
  helm-charts/interoperator/conf/sfservicebinding.yaml
  helm-charts/interoperator/conf/sfserviceinstance.yaml
  helm-charts/interoperator/templates/settings.yaml
  helm-charts/interoperator/templates/sfcluster.yaml
  helm-charts/interoperator/templates/sfplan.yaml
  helm-charts/interoperator/templates/sfservice.yaml
  helm-charts/interoperator/templates/sfservicebinding.yaml
  helm-charts/interoperator/templates/sfserviceinstance.yaml
  interoperator/Makefile
Labels: unscheduled

#812 [Interoperator] Making quota related values configurable
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#814 [Rel-branch]take service broker from request query in outdated API
  api-controllers/ServiceFabrikAdminController.js
Labels: unscheduled

#815 Making namespace based separation configurable
  config/settings.yml
  data-access-layer/eventmesh/src/ApiServerClient.js
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/values.yaml
  test/test_broker/eventmesh.ApiServerClient.spec.js
Labels: PipeLine:Green, unscheduled

#816 [interoperator] Unit Tests for #798
  interoperator/api/osb/v1alpha1/sfplan_types_test.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/internal/dynamic/dynamic_test.go
  interoperator/internal/renderer/factory/factory_test.go
  interoperator/internal/renderer/gotemplate/functions_test.go
  interoperator/internal/resources/helper_test.go
  interoperator/internal/resources/owner_reference_test.go
  interoperator/internal/resources/resources_test.go
Labels: DO NOT MERGE, unscheduled

#817 [helm-chart] Support imagePullSecret as helm parameter
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#819 Adding Helm Chart Package: 0.6.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.6.0.tgz
Labels: unscheduled

#818 Updating broker/Interoperator docker image versions
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#820 fixing minor typo
  package.json
Labels: unscheduled

#821 picking selected values for labels
  applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#822 [Release-branch] picking up selected labels from context
  api-controllers/ServiceBrokerApiController.js
  test/test_broker/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#824 Removing unneeded AbsRouteLookup patch from admin module
  applications/admin/index.js
  applications/osb-broker/src/server.js
Labels: unscheduled
