Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2021-12, with the labels that each got.

#1487 Updating broker/Interoperator docker image versions:0.20.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1488 Adding Helm Chart Package: 0.20.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.20.0.tgz
Labels: unscheduled

#1489 Fix sample SFService yaml, case issue with redirectURI
  docs/Interoperator.md
Labels: unscheduled

#1490 Document behavior of the SFPlan offboarding controller
  docs/Interoperator.md
Labels: unscheduled, documentation

#1332 Update Interoperator docs
  docs/Interoperator-Features.md
Labels: documentation

#1494 Support mTLS auth for quota app
  broker/core/utils/src/HttpClient.js
  broker/data-access-layer/quota/src/QuotaAPIMtlsAuthClient.js
  broker/data-access-layer/quota/src/index.js
  docs/Interoperator-authentication.md
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1498 HCPCFS-3190 Minor improvement to avoid synchronous binding timeouts
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/main.go
  interoperator/pkg/constants/constants.go
Labels: unscheduled

#1499 Updating broker/Interoperator docker image versions:0.21.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1500 Adding Helm Chart Package: 0.21.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.21.0.tgz
Labels: unscheduled
