Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2021-03, with the labels that each got.

#1270 Configure replicator worker count
  interoperator/controllers/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
Labels: PipeLine:Green, enhancement

#1263 Added multiple region support for quota
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/applications/osb-broker/src/api-controllers/routes/broker/index.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  broker/applications/quota-app/src/QuotaApiController.js
  broker/applications/quota-app/test/controllers.QuotaApiController.spec.js
  broker/config/settings.yml
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
  broker/data-access-layer/quota/src/BaseQuotaManager.js
  broker/data-access-layer/quota/src/QuotaAPIAuthClient.js
  broker/data-access-layer/quota/src/QuotaAPIClient.js
  broker/data-access-layer/quota/src/cf-platform-quota-manager/CFPlatformQuotaManager.js
  broker/data-access-layer/quota/src/cf-platform-quota-manager/index.js
  broker/data-access-layer/quota/src/index.js
  broker/data-access-layer/quota/src/k8s-platform-quota-manager/K8SPlatformQuotaManager.js
  broker/data-access-layer/quota/src/k8s-platform-quota-manager/index.js
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/templates/secret.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1261 Lazy Replication of SFService and SFPlan
  interoperator/controllers/multiclusterdeploy/setup_multiclusterdeploy.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller.go
  interoperator/controllers/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller_suite_test.go
  interoperator/controllers/multiclusterdeploy/sfservicesreplicator/sfservices_mcd_controller_test.go
Labels: PipeLine:Green, enhancement

#1276 Update base docker images
  broker/Dockerfile
  interoperator/Dockerfile
  operator-apis/Dockerfile
Labels: unscheduled

#1278 Updating broker/Interoperator docker image versions:0.13.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1279 Adding Helm Chart Package: 0.13.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.13.0.tgz
Labels: unscheduled

#1280 Rename the provisioner deployment
  helm-charts/interoperator/templates/provisioner.yaml
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/pkg/constants/constants.go
Labels: unscheduled

#1285 Bump Node version in Travis config
  .travis.yml
Labels: unscheduled

#1239 Development- Get Endpoints for instance and binding
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/applications/osb-broker/src/api-controllers/routes/broker/v2.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.GetEndpoints.spec.js
  broker/core/utils/src/commonVariables.js
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
Labels: DO NOT MERGE, unscheduled

#1141 Operator-api and quotaapp deployed conditionally
  helm-charts/interoperator/conf/resources.yaml
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/templates/operator_api_app.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/templates/scheduler.yaml
  helm-charts/interoperator/values.yaml
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/internal/config/config.go
  interoperator/internal/config/config_test.go
  interoperator/pkg/constants/constants.go
Labels: unscheduled

#1290 Upgrade lodash and pug
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/applications/scheduler/package.json
  broker/core/app-config/package.json
  broker/core/controllers/package.json
  broker/core/express-commons/package.json
  broker/core/logging/package.json
  broker/core/models/package.json
  broker/core/platform-managers/package.json
  broker/core/provisioner-services/package.json
  broker/core/scheduler-jobs/package.json
  broker/core/utils/package.json
  broker/data-access-layer/bosh/package.json
  broker/data-access-layer/broker-client/package.json
  broker/data-access-layer/cf/package.json
  broker/data-access-layer/db/package.json
  broker/data-access-layer/docker/package.json
  broker/data-access-layer/event-logger/package.json
  broker/data-access-layer/eventmesh/package.json
  broker/data-access-layer/iaas/package.json
  broker/data-access-layer/metering/package.json
  broker/data-access-layer/oob-manager/package.json
  broker/data-access-layer/quota/package.json
  broker/data-access-layer/service-agent/package.json
  broker/yarn.lock
Labels: dependencies, javascript

#1289 Propagate response from operator on Bind failure
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller.go
Labels: unscheduled

#1291 Fix container names in helm chart
  helm-charts/interoperator/templates/broker.yaml
  helm-charts/interoperator/templates/operator_api_app.yaml
  helm-charts/interoperator/templates/provisioner.yaml
  helm-charts/interoperator/templates/quota_app.yaml
Labels: unscheduled

#1292 Updating broker/Interoperator docker image versions:0.14.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1293 Adding Helm Chart Package: 0.14.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.14.0.tgz
Labels: unscheduled
