Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2021-04, with the labels that each got.

#1294 Remaining structural changes to support new osb version
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.GetEndpoints.spec.js
  broker/core/models/src/Plan.js
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/crds/sfplan.yaml
  helm-charts/interoperator/crds/sfserviceinstance.yaml
  helm-charts/interoperator/values.yaml
  interoperator/api/osb/v1alpha1/sfplan_types.go
  interoperator/api/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfplans.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfserviceinstances.yaml
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/internal/properties/properties.go
  interoperator/internal/properties/properties_test.go
Labels: PipeLine:Green

#1298 adding maintenance_info validation in provisioning and update requests
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/applications/osb-broker/src/api-controllers/routes/broker/v2.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  helm-charts/interoperator/crds/sfplan.yaml
  helm-charts/interoperator/crds/sfserviceinstance.yaml
  interoperator/api/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfplans.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfserviceinstances.yaml
Labels: PipeLine:Green

#1273 [OSB Spec Changes] Support maximum_polling_duration in service-plan
  broker/core/models/src/Plan.js
  helm-charts/interoperator/crds/sfplan.yaml
  interoperator/api/osb/v1alpha1/sfplan_types.go
  interoperator/api/osb/v1alpha1/sfplan_types_test.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfplans.yaml
Labels: PipeLine:Green

#1301 [rel-branch] fixing typo in instances_retrievable flag
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.GetEndpoints.spec.js
  broker/core/models/src/Service.js
  helm-charts/interoperator/crds/sfservice.yaml
  interoperator/api/osb/v1alpha1/sfservice_types.go
  interoperator/api/osb/v1alpha1/sfservice_types_test.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfservices.yaml
  interoperator/controllers/provisioners/sfplan/sfplan_controller_test.go
  interoperator/controllers/provisioners/sfservice/sfservice_controller_test.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller_test.go
  interoperator/internal/resources/helper_test.go
  interoperator/internal/services/services_test.go
  interoperator/pkg/watches/watches_test.go
Labels: unscheduled

#1300 fixing typo in instances_retrievable flag
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.GetEndpoints.spec.js
  broker/core/models/src/Service.js
  helm-charts/interoperator/crds/sfservice.yaml
  interoperator/api/osb/v1alpha1/sfservice_types.go
  interoperator/api/osb/v1alpha1/sfservice_types_test.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfservices.yaml
  interoperator/controllers/provisioners/sfplan/sfplan_controller_test.go
  interoperator/controllers/provisioners/sfservice/sfservice_controller_test.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller_test.go
  interoperator/internal/resources/helper_test.go
  interoperator/internal/services/services_test.go
  interoperator/pkg/watches/watches_test.go
Labels: PipeLine:Green, unscheduled

#1307 adding support for broker metadata as per new osb version
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.GetEndpoints.spec.js
  helm-charts/interoperator/crds/sfserviceinstance.yaml
  interoperator/api/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/api/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfserviceinstances.yaml
Labels: PipeLine:Green

#1310 Add validations to last_operation request
  broker/applications/osb-broker/src/api-controllers/routes/broker/v2.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#1311 Cleanup timed out Bindings
  broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
Labels: unscheduled

#1312 Updating broker/Interoperator docker image versions:0.15.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1313 Adding Helm Chart Package: 0.15.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.15.0.tgz
Labels: unscheduled

#1286 Fix json error in Response Error
  broker/applications/extensions/test/acceptance/service-fabrik-api-2.0.backups.director.spec.js
  broker/applications/extensions/test/acceptance/service-fabrik-api-2.0.instances.director.spec.js
  broker/applications/extensions/test/acceptance/service-fabrik-api.instances.director.spec.js
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  broker/core/express-commons/src/middleware/index.js
Labels: PipeLine:Green, bug
