Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2022-01, with the labels that each got.

#1516 update golang.org/x/text to v0.3.7
  interoperator/go.mod
  interoperator/go.sum
Labels: PipeLine:Green

#1505 Xrs + mtls support for interoperator broker & cis quota app
  broker/core/express-commons/src/middleware/BrokerMtlsAPIClient.js
  broker/core/express-commons/src/middleware/index.js
  broker/core/utils/src/HttpClient.js
  broker/data-access-layer/quota/src/QuotaAPIMtlsAuthClient.js
  broker/data-access-layer/quota/src/index.js
  docs/Interoperator-authentication.md
  helm-charts/interoperator/conf/settings.yaml
  helm-charts/interoperator/templates/quota_app.yaml
  helm-charts/interoperator/values.yaml
Labels: PipeLine:Green

#1517 Use "size" instead of "length" to get set's length
  broker/core/express-commons/src/middleware/index.js
Labels: unscheduled

#1495 Document plan upgrade validation
  docs/Interoperator-Features.md
Labels: documentation

#1518 Updating broker/Interoperator docker image versions:0.22.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1519 Adding Helm Chart Package: 0.22.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.22.0.tgz
Labels: unscheduled
