Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2022-03, with the labels that each got.

#1551 Library upgrade: Bump winston version from 3.3.3 to 3.6.0
  broker/core/logging/package.json
Labels: dependencies

#1550 library upgrade: Bump axios version from 0.21.4 to 0.25.0
  broker/core/utils/package.json
Labels: PipeLine:Green, dependencies

#1552 Library upgrades: Bump express version from 4.17.1 to 4.17.3
  broker/applications/admin/package.json
  broker/applications/deployment_hooks/package.json
  broker/applications/extensions/package.json
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
  broker/applications/reports/package.json
  broker/core/express-commons/package.json
  broker/yarn.lock
Labels: PipeLine:Green, dependencies

#1557 Remove unused rxjs & express_jwt libraries from osb_broker & quota_app.
  broker/applications/osb-broker/package.json
  broker/applications/quota-app/package.json
Labels: PipeLine:Green, dependencies

#1549 library upgrade: Bump camelcase-keys version from 6.2.2 to 7.0.2
  broker/applications/osb-broker/package.json
  broker/data-access-layer/eventmesh/package.json
Labels: PipeLine:Green, dependencies

#1556 Bump ajv from v6.12.6 to v8.10.0
  broker/applications/osb-broker/package.json
  broker/applications/osb-broker/src/api-controllers/middleware/index.js
  broker/applications/osb-broker/test/acceptance/service-broker-api.instances.director.spec.js
  docs/Interoperator-Features.md
Labels: PipeLine:Green, dependencies

#1564 Bump body-parser from 1.19.0 to 1.19.2
  broker/core/express-commons/package.json
Labels: PipeLine:Green, dependencies

#1563 Bump pubsub-js from 1.8.0 to 1.9.4
  broker/applications/scheduler/package.json
  broker/core/express-commons/package.json
  broker/core/scheduler-jobs/package.json
  broker/data-access-layer/db/package.json
  broker/data-access-layer/event-logger/package.json
  broker/data-access-layer/eventmesh/package.json
Labels: PipeLine:Green, dependencies

#1562 Bump winston-syslog from 2.4.4 to 2.5.0
  broker/core/logging/package.json
Labels: PipeLine:Green, dependencies

#1559 Bump helmet version from 4.1.0 to 5.0.2
  broker/core/express-commons/package.json
Labels: PipeLine:Green, dependencies

#1554 Bump helm version from v3.7.2 to v3.8.0
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/sfclusterreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/go.mod
  interoperator/go.sum
  operator-apis/go.mod
  operator-apis/go.sum
Labels: PipeLine:Green, dependencies

#1560 Bump moment from 2.27.0 to 2.29.1
  broker/applications/extensions/package.json
  broker/applications/operators/package.json
  broker/applications/scheduler/package.json
  broker/core/express-commons/package.json
  broker/core/scheduler-jobs/package.json
  broker/core/utils/package.json
  broker/data-access-layer/iaas/package.json
Labels: PipeLine:Green, dependencies

#1558 Bump js-yaml from 3.14.0 to 4.1.0
  broker/applications/extensions/package.json
  broker/applications/extensions/src/api-controllers/DashboardController.js
  broker/applications/operators/package.json
  broker/applications/operators/src/serviceflow-operator/SerialServiceFlowOperator.js
  broker/core/app-config/package.json
  broker/core/app-config/src/index.js
  broker/core/express-commons/package.json
  broker/core/provisioner-services/package.json
  broker/core/provisioner-services/src/DirectorService.js
  broker/core/provisioner-services/test/operators.DirectorService.ratelimits.spec.js
  broker/data-access-layer/bosh/package.json
  broker/data-access-layer/bosh/src/BoshDirectorClient.js
  broker/data-access-layer/bosh/src/manifest/Header.js
  broker/data-access-layer/bosh/test/bosh.BoshDirectorClient.spec.js
  broker/data-access-layer/event-logger/package.json
  broker/data-access-layer/event-logger/src/EventLogInterceptor.js
  broker/data-access-layer/eventmesh/package.json
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
Labels: PipeLine:Green, dependencies

#1572 Remove dependency of cert in mTLS disabled quota app
  helm-charts/interoperator/templates/quota_app.yaml
Labels: PipeLine:Green

#1584 Updating broker/Interoperator docker image versions:0.22.1
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1585 Adding Helm Chart Package: 0.22.1
  helm-charts/index.yaml
  helm-charts/interoperator-0.22.1.tgz
Labels: unscheduled

#1570 Remove dependency of cert in mTLS disabled quota app
  helm-charts/interoperator/templates/quota_app.yaml
Labels: PipeLine:Green

#1569 Bump kubernetes/client-node from v0.12.3 to v0.16.3
  broker/applications/osb-broker/test/acceptance/service-broker-api-2.0.instances.director.spec.js
  broker/data-access-layer/eventmesh/package.json
  broker/data-access-layer/eventmesh/src/ApiServerClient.js
Labels: PipeLine:Green, dependencies

#1587 Upgrade selfsigned library from v1.10.7 to v2.0.0
  broker/core/provisioner-services/package.json
Labels: unscheduled

#1589 HCPCFS-3070 updating .helmignore file
  helm-charts/interoperator/.helmignore
Labels: scheduled

#1590 Update node to 16.14 from 16.10
  .travis.yml
  broker/Dockerfile
Labels: accepted, scheduled, docker

#1555 Bump prometheus/client_golang from v1.11.0 to v1.12.1
  interoperator/go.mod
  interoperator/go.sum
  operator-apis/go.mod
  operator-apis/go.sum
Labels: scheduled, dependencies, go

#1532 prevent accidental deletion of sfplans by users.
  interoperator/controllers/multiclusterdeploy/setup_multiclusterdeploy.go
  interoperator/controllers/multiclusterdeploy/sfplanoffboarding/offboarding_sfplan_controller.go
  interoperator/controllers/multiclusterdeploy/sfplanoffboarding/offboarding_sfplan_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfplanoffboarding/suite_test.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/pkg/constants/constants.go
Labels: scheduled, go

#1597 Adding Helm Chart Package: 0.23.0
  helm-charts/index.yaml
  helm-charts/interoperator-0.23.0.tgz
Labels: unscheduled

#1596 Updating broker/Interoperator docker image versions:0.23.0
  helm-charts/interoperator/Chart.yaml
  helm-charts/interoperator/values.yaml
Labels: unscheduled

#1594 Upgrade alicloud/pop-core from v1.7.9 to v1.7.10
  broker/data-access-layer/iaas/package.json
Labels: PipeLine:Green, dependencies
