Repository cloudfoundry/service-fabrik-broker, pull requests merged in 2023-12, with the labels that each got.

#1998 Kubeconfig rotation documentation
  README.md
  docs/Interoperator-Features.md
Labels: documentation

#1982 Kubeconfig Rotation
  helm-charts/interoperator/templates/multiclusterdeployer.yaml
  helm-charts/interoperator/values.yaml
  interoperator/Dockerfile
  interoperator/kubeconfig_rotation/go.mod
  interoperator/kubeconfig_rotation/go.sum
  interoperator/kubeconfig_rotation/main.go
Labels: enhancement, PipeLine:Green, go

#1994 fix golint issues
  interoperator/api/osb/v1alpha1/sfservicebinding_types.go
  interoperator/api/osb/v1alpha1/sfserviceinstance_types.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingmetrics/sfservicebindingmetrics_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancemetrics/sfserviceinstancemetrics_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancemetrics/sfserviceinstancemetrics_controller_test.go
Labels: enhancement, go

#1986 Update/k8s libraries
  helm-charts/interoperator/crds/sfcluster.yaml
  helm-charts/interoperator/crds/sfplan.yaml
  helm-charts/interoperator/crds/sfservice.yaml
  helm-charts/interoperator/crds/sfservicebinding.yaml
  helm-charts/interoperator/crds/sfserviceinstance.yaml
  interoperator/Makefile
  interoperator/api/osb/v1alpha1/zz_generated.deepcopy.go
  interoperator/api/resource/v1alpha1/mock_sfcluster/mock_sfcluster.go
  interoperator/api/resource/v1alpha1/zz_generated.deepcopy.go
  interoperator/config/crd/bases/osb.servicefabrik.io_sfplans.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfservicebindings.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfserviceinstances.yaml
  interoperator/config/crd/bases/osb.servicefabrik.io_sfservices.yaml
  interoperator/config/crd/bases/resource.servicefabrik.io_sfclusters.yaml
  interoperator/controllers/multiclusterdeploy/offboarding/offboarding_controller.go
  interoperator/controllers/multiclusterdeploy/offboarding/suite_test.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller.go
  interoperator/controllers/multiclusterdeploy/provisioner/provisioner_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/sfclusterreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfclusterreplicator/suite_test.go
  interoperator/controllers/multiclusterdeploy/sfplanoffboarding/suite_test.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingmetrics/sfservicebindingmetrics_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfservicebindingreplicator/sfservicebindingreplicator_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancemetrics/sfserviceinstancemetrics_controller_test.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller.go
  interoperator/controllers/multiclusterdeploy/sfserviceinstancereplicator/sfserviceinstancereplicator_controller_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/internal_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/manager_test.go
  interoperator/controllers/multiclusterdeploy/watchmanager/watchmanager_suite_test.go
  interoperator/controllers/provisioners/sfclusterusage/sfclusterusage_controller.go
  interoperator/controllers/provisioners/sfclusterusage/suite_test.go
  interoperator/controllers/provisioners/sfplan/sfplan_controller_test.go
  interoperator/controllers/provisioners/sfservice/sfservice_controller_test.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller.go
  interoperator/controllers/provisioners/sfservicebinding/sfservicebinding_controller_test.go
  interoperator/controllers/provisioners/sfservicebindingcleaner/sfservicebindingcleaner_controller_test.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller.go
  interoperator/controllers/provisioners/sfserviceinstance/sfserviceinstance_controller_test.go
  interoperator/controllers/schedulers/sfdefaultscheduler/sfdefaultscheduler_controller_test.go
  interoperator/controllers/schedulers/sflabelselectorscheduler/sflabelselectorscheduler_controller_test.go
  interoperator/controllers/schedulers/sfserviceinstancecounter/sfserviceinstancecounter_controller_test.go
  interoperator/controllers/schedulers/sfserviceinstanceupdater/sfserviceinstanceupdater_controller.go
  interoperator/controllers/schedulers/sfserviceinstanceupdater/sfserviceinstanceupdater_controller_test.go
  interoperator/go.mod
  interoperator/go.sum
  interoperator/hack/boilerplate.go.txt
  interoperator/main.go
  interoperator/pkg/cluster/registry/registry_suite_test.go
  operator-apis/go.mod
  operator-apis/go.sum
  operator-apis/internal/handlers/handlers_suite_test.go
Labels: PipeLine:Green, dependencies, go
